import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  de: {
    // Navigation
    'nav.cockpit': 'Cockpit',
    'nav.projects': 'Projekte',
    'nav.products': 'Produkte',
    'nav.customers': 'Kunden',
    'nav.collections': 'Sammlungen',
    'nav.reports': 'Reports',
    'nav.administration': 'Administration',
    'nav.admin': 'Benutzerverwaltung',
    'nav.dataHub': 'Datenhub',
    'nav.logout': 'Abmelden',
    'nav.applications': 'Applikationen',
    'nav.superAdmin': 'Super Admin',
    'nav.accessLogs': 'Zugriffsprotokolle',
    'nav.utility': 'Werkzeuge',
    
    // Page Titles
    'page.projects': 'Projekte',
    'page.products': 'Produkte',
    'page.customers': 'Kunden',
    'page.collections': 'Sammlungen',
    'page.applications': 'Applikationen',
    'page.admin': 'Admin',
    'page.reports': 'Reports',
    'page.dataHub': 'Datenhub',
    'page.superAdmin': 'Super Admin',
    'page.dashboard': 'Dashboard',
    'page.settings': 'Einstellungen',
    'page.crossSells': 'Cross Sells',
    
    // Search
    'search.placeholder': 'Suche nach Projekten, Produkten, Kunden...',
    'search.noResults': 'Keine Ergebnisse gefunden',
    'search.projects': 'Projekte',
    'search.products': 'Produkte',
    'search.customers': 'Kunden',
    'search.applications': 'Applikationen',
    'search.collections': 'Sammlungen',
    'search.searchProjects': 'Projekte suchen...',
    'search.searchProducts': 'Produkte suchen...',
    'search.searchCustomers': 'Kunde suchen...',
    'search.searchApplications': 'Applikationen suchen...',
    'search.searchCrossSells': 'Cross-Sells suchen...',
    'search.searchCollections': 'Sammlungen suchen...',
    
    // User Preferences
    'userPrefs.title': 'Benutzereinstellungen',
    'userPrefs.theme': 'Design',
    'userPrefs.light': 'Hell',
    'userPrefs.dark': 'Dunkel',
    'userPrefs.system': 'System',
    'userPrefs.language': 'Sprache',
    
    // Preferences Popover
    'prefs.title': 'Benutzer Präferenzen',
    'prefs.subtitle': 'Passen Sie Ihre Inhalts- und Anzeigeeinstellungen an.',
    'prefs.content': 'Inhalte',
    'prefs.view': 'Ansicht',
    'prefs.functions': 'Funktionen',
    'prefs.targetApplications': 'Zielapplikationen',
    'prefs.productFamilies': 'Produktfamilien',
    'prefs.manufacturers': 'Hersteller',
    'prefs.none': 'Keine',
    'prefs.saved': 'Präferenzen gespeichert',
    'prefs.saveError': 'Fehler beim Speichern der Präferenzen',
    'prefs.saving': 'Speichern...',
    'prefs.recentProjectsCount': 'Anzahl "Zuletzt" Projekte',
    'prefs.recentProjectsDesc': 'Wie viele zuletzt angesehene Projekte sollen angezeigt werden?',
    'prefs.selectCount': 'Anzahl wählen',
    'prefs.projects': 'Projekte',
    'prefs.autoLogoffTime': 'Auto-Logoff Zeit',
    'prefs.autoLogoffDesc': 'Nach wie vielen Minuten ohne Aktivität sollen Sie automatisch abgemeldet werden?',
    'prefs.selectTime': 'Zeit wählen',
    'prefs.minutes': 'Minuten',
    
    // Notifications
    'notifications.title': 'Benachrichtigungen',
    'notifications.markAllRead': 'Alle als gelesen markieren',
    'notifications.noNotifications': 'Keine Benachrichtigungen',
    'notifications.showsLast7Days': 'Zeigt Aktivitäten der letzten 7 Tage',
    
    // Dashboard
    'dashboard.welcome': 'Willkommen',
    'dashboard.statistics': 'Statistiken',
    'dashboard.recentProjects': 'Aktuelle Projekte',
    'dashboard.actionItems': 'Aktionspunkte',
    'dashboard.gettingStarted': 'Erste Schritte',
    
    // Widget Settings
    'widgetSettings.customize': 'Dashboard anpassen',
    'widgetSettings.customizeWidgets': 'Widgets anpassen',
    'widgetSettings.customizeDesc': 'Wählen Sie, welche Widgets angezeigt werden sollen. Ziehen Sie sie, um die Reihenfolge zu ändern.',
    'widgetSettings.projects': 'Projekte',
    'widgetSettings.actionItems': 'Action Items',
    'widgetSettings.npiProducts': 'NPI Produkte',
    'widgetSettings.statistics': 'Statistiken',
    'widgetSettings.optimizationStatus': 'Optimierungsstatus',
    'widgetSettings.loginActivity': 'Login-Aktivität (Admin)',
    'widgetSettings.accessStats': 'Access Statistiken (Admin)',
    'widgetSettings.addedProducts': 'Ergänzte Produkte',
    'widgetSettings.gettingStarted': 'Erste Schritte',
    'widgetSettings.halfWidth': 'Halbe Breite',
    'widgetSettings.fullWidth': 'Volle Breite',
    
    // Common Actions
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.export': 'Exportieren',
    'common.import': 'Importieren',
    'common.loading': 'Lädt...',
    'common.add': 'Hinzufügen',
    'common.remove': 'Entfernen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Zurück',
    'common.configure': 'Konfigurieren',
    'common.reset': 'Zurücksetzen',
    'common.showAll': 'Alle anzeigen',
    'common.show': 'Anzeigen',
    'common.hide': 'Ausblenden',
    'common.all': 'Alle',
    'common.none': 'Keine',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.confirm': 'Bestätigen',
    'common.reject': 'Ablehnen',
    'common.details': 'Details',
    'common.actions': 'Aktionen',
    'common.noData': 'Keine Daten vorhanden',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    
    // Table Headers - Projects
    'table.projectName': 'Projektname',
    'table.customer': 'Kunde',
    'table.application': 'Applikation',
    'table.applications': 'Applikationen',
    'table.product': 'Produkt',
    'table.products': 'Produkte',
    'table.status': 'Status',
    'table.optimizationStatus': 'Optimierungsstatus',
    'table.created': 'Erstellt',
    'table.lastModified': 'Zuletzt geändert',
    'table.productsInProject': 'Produkte im Projekt',
    'table.crossSellOpportunities': 'Cross-Sell Opportunities',
    
    // Table Headers - Products
    'table.component': 'Bauteil',
    'table.manufacturer': 'Hersteller',
    'table.productFamily': 'Produktfamilie',
    'table.description': 'Beschreibung',
    'table.tags': 'Tags',
    'table.price': 'Preis',
    'table.priceTooltip': 'in €/pcs',
    'table.leadTime': 'Lieferzeit',
    'table.leadTimeTooltip': 'in Wochen',
    'table.inventory': 'Lagerbestand',
    'table.inventoryTooltip': 'in pcs',
    'table.crossSells': 'Cross-Sells',
    'table.link': 'Link',
    'table.alternatives': 'Alternativen',
    'table.reason': 'Grund',
    'table.score': 'Score',
    'table.recommendation': 'Empfehlung',
    'table.action': 'Aktion',
    
    // Table Headers - Customers
    'table.customerName': 'Kunde',
    'table.industry': 'Branche',
    'table.country': 'Land',
    'table.city': 'Stadt',
    'table.category': 'Kategorie',
    'table.projectCount': 'Projekte',
    
    // Optimization Status
    'status.new': 'Neu',
    'status.open': 'Offen',
    'status.review': 'Prüfung',
    'status.validation': 'Validierung',
    'status.completed': 'Abgeschlossen',
    'status.identified': 'Identifiziert',
    'status.suggested': 'Vorgeschlagen',
    'status.accepted': 'Akzeptiert',
    'status.registered': 'Registriert',
    'status.rejected': 'Abgelehnt',
    
    // Filter Options
    'filter.all': 'Alle',
    'filter.allProjects': 'Alle Projekte',
    'filter.allProducts': 'Alle Produkte',
    'filter.allCustomers': 'Alle Kunden',
    'filter.allApplications': 'Alle Applikationen',
    'filter.allCategories': 'Alle Kategorien',
    'filter.allIndustries': 'Alle Branchen',
    'filter.allCountries': 'Alle Länder',
    'filter.allCities': 'Alle Städte',
    'filter.favorites': 'Favoriten',
    'filter.recent': 'Zuletzt',
    'filter.status': 'Status',
    'filter.productFamily': 'Produktfamilie',
    'filter.manufacturer': 'Hersteller',
    'filter.lifecycle': 'Lebenszyklus',
    'filter.npiOnly': 'Nur NPI',
    'filter.topOnly': 'Nur Top',
    
    // Pagination
    'pagination.results': 'Ergebnisse',
    'pagination.resultsPerPage': 'Ergebnisse pro Seite',
    'pagination.of': 'von',
    'pagination.previous': 'Zurück',
    'pagination.next': 'Weiter',
    'pagination.page': 'Seite',
    
    // Dashboard Widgets
    'widget.projects': 'Projekte',
    'widget.statistics': 'Statistiken',
    'widget.actionItems': 'Aktionspunkte',
    'widget.gettingStarted': 'Erste Schritte',
    'widget.optimizationStatus': 'Projekte nach Optimierungsstatus',
    'widget.npiProducts': 'NPI Produkte',
    'widget.addedProducts': 'Hinzugefügte Produkte',
    'widget.loginActivity': 'Login Aktivität',
    'widget.accessStats': 'Zugriffs-Statistiken',
    'widget.search': 'Suche',
    
    // NPI Products Widget
    'npiProducts.title': 'NPI Produkte',
    'npiProducts.noProducts': 'Keine NPI-Produkte vorhanden',
    
    // Project Detail
    'project.metadata': 'Projektdetails',
    'project.createdAt': 'Erstellt',
    'project.customer': 'Kunde',
    'project.application': 'Applikation',
    'project.products': 'Produkte',
    'project.crossSells': 'Cross-Sells',
    'project.alternatives': 'Alternativen',
    'project.noProducts': 'Keine Produkte in diesem Projekt',
    'project.noCrossSells': 'Keine Cross-Sell Opportunities verfügbar',
    'project.addProduct': 'Produkt hinzufügen',
    'project.removeProduct': 'Produkt entfernen',
    
    // Product Detail
    'product.details': 'Produktdetails',
    'product.addToCollection': 'Zur Sammlung hinzufügen',
    'product.selectCollection': 'Sammlung auswählen',
    'product.createCollection': 'Neue Sammlung erstellen',
    'product.collectionName': 'Sammlungsname',
    'product.collectionCreated': 'Sammlung erstellt',
    'product.addedToCollection': 'Produkt zur Sammlung hinzugefügt',
    'product.alreadyInCollection': 'Produkt ist bereits in dieser Sammlung',
    
    // Customer Detail
    'customer.details': 'Kundendetails',
    'customer.location': 'Standort',
    'customer.viewProjects': 'Projekte anzeigen',
    
    // Dialogs
    'dialog.confirmDelete': 'Löschen bestätigen',
    'dialog.deleteMessage': 'Möchten Sie diesen Eintrag wirklich löschen?',
    'dialog.inviteUser': 'Benutzer einladen',
    'dialog.addToCollection': 'Zur Sammlung hinzufügen',
    'dialog.removeReason': 'Grund für Entfernung',
    
    // Toast Messages
    'toast.success': 'Erfolgreich',
    'toast.error': 'Fehler',
    'toast.saved': 'Gespeichert',
    'toast.deleted': 'Gelöscht',
    'toast.added': 'Hinzugefügt',
    'toast.removed': 'Entfernt',
    'toast.updated': 'Aktualisiert',
    'toast.loadError': 'Fehler beim Laden',
    'toast.saveError': 'Fehler beim Speichern',
    'toast.deleteError': 'Fehler beim Löschen',
    
    // Admin
    'admin.users': 'Benutzer',
    'admin.inviteUser': 'Benutzer einladen',
    'admin.role': 'Rolle',
    'admin.lastLogin': 'Letzter Login',
    'admin.pendingInvitation': 'Einladung ausstehend',
    'admin.deleteUser': 'Benutzer löschen',
    'admin.userManagement': 'Benutzerverwaltung',
    
    // Removal Reasons
    'removal.technicalFit': 'Technischer Fit',
    'removal.commercialFit': 'Commercial Fit',
    'removal.otherSupplier': 'Anderer Lieferant',
    'removal.noNeed': 'Kein Bedarf',
    'removal.other': 'Sonstige',
    
    // Product Lifecycle
    'lifecycle.comingSoon': 'Coming Soon',
    'lifecycle.active': 'Active',
    'lifecycle.nfnd': 'NFND',
    'lifecycle.discontinued': 'Discontinued',
    
    // Empty States
    'empty.projects': 'Keine Projekte gefunden',
    'empty.products': 'Keine Produkte gefunden',
    'empty.customers': 'Keine Kunden gefunden',
    'empty.collections': 'Keine Sammlungen gefunden',
    'empty.applications': 'Keine Applikationen gefunden',
    'empty.crossSells': 'Keine Cross-Sells verfügbar',
    'empty.alternatives': 'Keine Alternativen verfügbar',
    
    // Column Visibility
    'columns.configure': 'Spalten konfigurieren',
    'columns.reset': 'Zurücksetzen',
    'columns.showAll': 'Alle anzeigen',
    'columns.hideAll': 'Alle ausblenden',
    
    // Quick Filters - Projects
    'quickFilter.all': 'Alle',
    'quickFilter.favorites': 'Favoriten',
    'quickFilter.recent': 'Zuletzt',
    'quickFilter.new': 'Neu',
    'quickFilter.review': 'Prüfen',
    
    // Collections
    'collections.title': 'Sammlungen',
    'collections.new': 'Neue Sammlung',
    'collections.edit': 'Sammlung bearbeiten',
    'collections.create': 'Neue Sammlung erstellen',
    'collections.name': 'Name',
    'collections.description': 'Beschreibung (optional)',
    'collections.visibility': 'Sichtbarkeit',
    'collections.visibilityPrivate': 'Nur für mich',
    'collections.visibilitySelected': 'Ausgewählte Nutzer',
    'collections.visibilityOrganization': 'Gesamte Organisation',
    'collections.shareWith': 'Mit Nutzern teilen',
    'collections.selectUser': 'Nutzer auswählen...',
    'collections.products': 'Produkte',
    'collections.createdBy': 'Erstellt von',
    'collections.noCollections': 'Noch keine Sammlungen vorhanden',
    'collections.noProducts': 'Diese Sammlung enthält keine Produkte',
    'collections.confirmDelete': 'Sammlung wirklich löschen?',
    'collections.updated': 'Sammlung aktualisiert',
    'collections.created': 'Sammlung erstellt',
    'collections.deleted': 'Sammlung gelöscht',
    'collections.productRemoved': 'Produkt entfernt',
    'collections.saveError': 'Fehler beim Speichern',
    'collections.selectProducts': 'Produkte auswählen',
    
    // Applications
    'applications.title': 'Applikationen',
    'applications.relatedProduct': 'Zugehöriges Produkt',
    'applications.noApplications': 'Keine Applikationen gefunden',
    'applications.tryDifferentSearch': 'Versuchen Sie einen anderen Suchbegriff',
    'applications.startUpload': 'Beginnen Sie mit dem Hochladen von Applikationsdaten',
    'applications.details': 'Applikationsdetails und Informationen',
    'applications.industry': 'Industrie',
    'applications.trends': 'Trends',
    'applications.productFamilies': 'Product Families',
    'applications.blockDiagram': 'Blockdiagramm',
    'applications.noDetails': 'Keine detaillierten Informationen für diese Applikation verfügbar.',
    
    // Action Items
    'actionItems.title': 'Action Items',
    'actionItems.new': 'Neu',
    'actionItems.edit': 'Action Item bearbeiten',
    'actionItems.create': 'Neues Action Item',
    'actionItems.titleLabel': 'Titel',
    'actionItems.titlePlaceholder': 'Titel des Action Items',
    'actionItems.descriptionLabel': 'Beschreibung',
    'actionItems.descriptionPlaceholder': 'Optionale Beschreibung',
    'actionItems.priority': 'Priorität',
    'actionItems.priorityLow': 'Niedrig',
    'actionItems.priorityMedium': 'Mittel',
    'actionItems.priorityHigh': 'Hoch',
    'actionItems.statusOpen': 'Offen',
    'actionItems.statusInProgress': 'In Bearbeitung',
    'actionItems.statusCompleted': 'Abgeschlossen',
    'actionItems.assignedTo': 'Zugewiesen an',
    'actionItems.assignMyself': 'Mich selbst',
    'actionItems.assignment': 'Zuordnung (optional)',
    'actionItems.project': 'Projekt',
    'actionItems.customer': 'Kunde',
    'actionItems.selectProject': 'Projekt auswählen...',
    'actionItems.selectCustomer': 'Kunde auswählen...',
    'actionItems.dueDate': 'Fälligkeitsdatum (optional)',
    'actionItems.noItems': 'Noch keine Action Items. Erstellen Sie Ihr erstes!',
    'actionItems.sortByCreation': 'Nach Erstellung',
    'actionItems.sortByPriority': 'Nach Priorität',
    'actionItems.sortByDueDate': 'Nach Fälligkeit',
    'actionItems.updated': 'Action Item aktualisiert',
    'actionItems.created': 'Action Item erstellt',
    'actionItems.deleted': 'Action Item gelöscht',
    'actionItems.saveError': 'Fehler beim Speichern',
    
    // Search Widget
    'searchWidget.title': 'Opportunity Optimizer',
    'searchWidget.subtitle': 'Finden Sie Cross-Selling und Up-Selling Potenziale in Ihren Kundenprojekten',
    'searchWidget.placeholder': 'Suchen Sie nach Kunden, Projekten, Applikationen oder Produkten...',
    'searchWidget.searching': 'Suche nach',
    'searchWidget.noResults': 'Keine Ergebnisse gefunden. Laden Sie Daten im Datenhub hoch, um zu beginnen.',
    'searchWidget.recentlyViewed': 'Zuletzt angesehen',
    'searchWidget.crossSellOpportunities': 'Cross-Selling Möglichkeiten',
    
    // Statistics Widget
    'statistics.projects': 'Projekte',
    'statistics.products': 'Produkte',
    'statistics.crossSelling': 'Cross-Selling',
    'statistics.inDatabase': 'In der Datenbank',
    'statistics.available': 'Verfügbar',
    'statistics.opportunities': 'Möglichkeiten',
    'statistics.projectOverview': 'Projektübersicht',
    'statistics.allActiveProjects': 'Alle aktiven Kundenprojekte in der Datenbank',
    'statistics.productCatalog': 'Produktkatalog',
    'statistics.allAvailableProducts': 'Alle verfügbaren Produkte für Optimierungen',
    'statistics.crossSellingPotential': 'Cross-Selling Potenzial',
    'statistics.identifiedOpportunities': 'Identifizierte Verkaufschancen für zusätzliche Produkte',
    
    // Optimization Status Widget
    'optimizationStatus.title': 'Projekte nach Optimierungsstatus',
    'optimizationStatus.allTenants': 'Alle Mandanten',
    'optimizationStatus.aggregatedDistribution': 'Aggregierte Verteilung aller Projekte aus allen Mandanten nach Status',
    'optimizationStatus.distribution': 'Verteilung der Projekte nach Status im ausgewählten Zeitraum',
    'optimizationStatus.total': 'Gesamt',
    'optimizationStatus.totalAllTenants': 'Gesamt (Alle Mandanten)',
    'optimizationStatus.projects': 'Projekte',
    'optimizationStatus.projectsCrossTenanت': 'Projekte mandantenübergreifend',
    'optimizationStatus.noProjectsInTenants': 'Keine Projekte in den Mandanten gefunden',
    'optimizationStatus.noProjectsInTimeframe': 'Keine Projekte im ausgewählten Zeitraum',
    'optimizationStatus.ensureTenantsHaveData': 'Stellen Sie sicher, dass Mandanten Projektdaten hochgeladen haben',
    'optimizationStatus.tryLongerTimeframe': 'Versuchen Sie einen längeren Zeitraum oder laden Sie Projektdaten hoch',
    'optimizationStatus.distributionByStatus': 'Verteilung nach Status',
    'optimizationStatus.projectCount': 'Anzahl Projekte',
    'optimizationStatus.1month': '1 Monat',
    'optimizationStatus.3months': '3 Monate',
    'optimizationStatus.6months': '6 Monate',
    'optimizationStatus.12months': '12 Monate',
    
    // Added Products Widget
    'addedProducts.title': 'Hinzugefügte Produkte nach Status',
    'addedProducts.description': 'Cross-Sells und Alternativen, die zu Projekten hinzugefügt wurden',
    'addedProducts.noProducts': 'Keine hinzugefügten Produkte im ausgewählten Zeitraum',
    'addedProducts.addProductsHint': 'Fügen Sie Cross-Sells oder Alternativen zu Projekten hinzu, um sie hier zu sehen',
    'addedProducts.total': 'Gesamt',
    'addedProducts.crossSells': 'Cross-Sells',
    'addedProducts.alternatives': 'Alternativen',
    'addedProducts.distributionByStatus': 'Verteilung nach Status',
    'addedProducts.1month': '1 Monat',
    'addedProducts.3months': '3 Monate',
    'addedProducts.6months': '6 Monate',
    'addedProducts.12months': '12 Monate',
    
    // Login Activity Widget
    'loginActivity.title': 'Login-Aktivität',
    'loginActivity.description': 'Login-Verlauf im ausgewählten Zeitraum',
    'loginActivity.totalLogins': 'Gesamt Logins',
    'loginActivity.activeUsers': 'Aktive Benutzer',
    'loginActivity.avgLoginsPerUser': 'Ø Logins/Benutzer',
    'loginActivity.avgLoginsPerDay': 'Ø Logins/Tag',
    'loginActivity.logins': 'Logins',
    'loginActivity.timeRange': 'Zeitraum',
    'loginActivity.granularity': 'Granularität',
    'loginActivity.daily': 'Täglich',
    'loginActivity.weekly': 'Wöchentlich',
    'loginActivity.monthly': 'Monatlich',
    'loginActivity.week': 'KW',
    'loginActivity.1month': '1 Monat',
    'loginActivity.3months': '3 Monate',
    'loginActivity.6months': '6 Monate',
    'loginActivity.12months': '12 Monate',
    
    // Access Stats Widget
    'accessStats.title': 'Access Statistiken',
    'accessStats.description': 'Benutzeraktivitäten im ausgewählten Zeitraum',
    'accessStats.totalEvents': 'Gesamt Events',
    'accessStats.activeUsers': 'Aktive Benutzer',
    'accessStats.avgEventsPerUser': 'Ø Events/Benutzer',
    'accessStats.count': 'Anzahl',
    'accessStats.timeRange': 'Zeitraum',
    'accessStats.logins': 'Logins',
    'accessStats.logouts': 'Logouts',
    'accessStats.pageViews': 'Seitenaufrufe',
    'accessStats.actions': 'Aktionen',
    'accessStats.1month': '1 Monat',
    'accessStats.3months': '3 Monate',
    'accessStats.6months': '6 Monate',
    'accessStats.12months': '12 Monate',
    
    // Getting Started Widget
    'gettingStarted.title': 'Erste Schritte',
    'gettingStarted.step1Title': 'Daten hochladen',
    'gettingStarted.step1Description': 'Beginnen Sie mit dem Upload Ihrer Kundenprojekte und Produktdaten im Datenhub',
    'gettingStarted.step2Title': 'Daten durchsuchen',
    'gettingStarted.step2Description': 'Nutzen Sie die Suche, um Cross-Selling und Alternative Produktempfehlungen zu finden',
    'gettingStarted.step3Title': 'Verkaufschancen nutzen',
    'gettingStarted.step3Description': 'Analysieren Sie die Vorschläge und kontaktieren Sie Ihre Kunden mit neuen Angeboten',
    
    // Product Status
    'productStatus.identified': 'Identifiziert',
    'productStatus.suggested': 'Vorgeschlagen',
    'productStatus.accepted': 'Akzeptiert',
    'productStatus.registered': 'Registriert',
    'productStatus.rejected': 'Abgelehnt',
    
    // Projects Widget
    'projectsWidget.showAll': 'Alle {count} Projekte anzeigen',
    'projectsWidget.noProjects': 'Keine Projekte gefunden',
    'projectsWidget.customer': 'Kunde',
    'projectsWidget.application': 'Applikation',
    'projectsWidget.created': 'Erstellt',
    'projectsWidget.modified': 'Geändert',
    'projectsWidget.status': 'Status',
    
    // Admin Page
    'admin.title': 'Benutzerverwaltung',
    'admin.description': 'Verwalten Sie Benutzer, deren Rollen und Einstellungen',
    'admin.usersTab': 'Benutzer',
    'admin.preferencesTab': 'Benutzer-Einstellungen',
    'admin.inviteButton': 'Benutzer einladen',
    'admin.inviteDialogTitle': 'Neuen Benutzer einladen',
    'admin.inviteDialogDesc': 'Senden Sie eine Einladungs-E-Mail an einen neuen Benutzer',
    'admin.firstName': 'Vorname',
    'admin.lastName': 'Nachname',
    'admin.email': 'E-Mail-Adresse',
    'admin.roleLabel': 'Rolle',
    'admin.roleUser': 'Benutzer',
    'admin.roleTenantAdmin': 'Tenant Admin',
    'admin.registeredUsers': 'Bereits registrierte Benutzer',
    'admin.registeredUsersHint': 'Diese E-Mail-Adressen sind bereits registriert',
    'admin.sendInvite': 'Einladung senden',
    'admin.sending': 'Wird gesendet...',
    'admin.totalUsers': 'Benutzer gesamt',
    'admin.registeredUsersCount': 'Registrierte Benutzer',
    'admin.admins': 'Administratoren',
    'admin.adminsCount': 'Mit Admin-Rechten',
    'admin.recentActivity': 'Kürzlich aktiv',
    'admin.lastDays': 'Letzte 7 Tage',
    'admin.searchUsers': 'Benutzer suchen...',
    'admin.name': 'Name',
    'admin.registered': 'Registriert',
    'admin.noUsers': 'Keine Benutzer gefunden',
    'admin.resendInvite': 'Einladung erneut senden',
    'admin.resendInviteShort': 'Einladung',
    'admin.makeAdmin': 'Als Admin setzen',
    'admin.removeAdmin': 'Admin entfernen',
    'admin.roleAdmin': 'Admin',
    'admin.confirmDeleteTitle': 'Benutzer löschen',
    'admin.confirmDeleteDesc': 'Sind Sie sicher, dass Sie den Benutzer "{email}" löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'admin.deleting': 'Wird gelöscht...',
    'admin.noTenantSelected': 'Kein Mandant ausgewählt. Bitte wählen Sie einen Mandanten in der Seitenleiste aus.',
    'admin.backToSuperAdmin': 'Zurück zum Super-Admin Dashboard',
    'admin.activeUsers': 'Aktive Benutzer',
    'admin.last30Days': 'Letzte 30 Tage',
    'admin.allUsers': 'Alle Benutzer',
    'admin.manageUsersPermissions': 'Verwalten Sie Benutzer und deren Berechtigungen',
    'admin.searchByEmailOrName': 'Nach E-Mail oder Name suchen...',
    'admin.actionsColumn': 'Aktionen',
    'admin.noUsersFoundFor': 'Keine Benutzer gefunden für',
    'admin.noUsersAvailable': 'Keine Benutzer vorhanden',
    'admin.deleteUserTitle': 'Benutzer löschen?',
    'admin.deleteUserConfirm': 'Sind Sie sicher, dass Sie den Benutzer löschen möchten?',
    'admin.deleteUserWarning': 'Diese Aktion kann nicht rückgängig gemacht werden. Alle Daten des Benutzers werden dauerhaft gelöscht.',
    
    // User Preferences Viewer
    'userPrefsViewer.title': 'Benutzer-Einstellungen',
    'userPrefsViewer.description': 'Übersicht aller Benutzer-Präferenzen im Mandanten',
    'userPrefsViewer.usersWithDashboard': 'Benutzer mit Dashboard-Einstellungen',
    'userPrefsViewer.usersWithColumns': 'Benutzer mit Spalten-Einstellungen',
    'userPrefsViewer.ofUsers': 'von {count} Benutzern',
    'userPrefsViewer.totalSettings': 'Gesamt-Einstellungen',
    'userPrefsViewer.configurations': 'Konfigurationen',
    'userPrefsViewer.userOverview': 'Benutzer-Übersicht',
    'userPrefsViewer.userOverviewDesc': 'Dashboard- und Spalten-Einstellungen pro Benutzer',
    'userPrefsViewer.dashboard': 'Dashboard',
    'userPrefsViewer.columns': 'Spalten',
    'userPrefsViewer.noDashboardSettings': 'Keine Dashboard-Einstellungen',
    'userPrefsViewer.noColumnSettings': 'Keine Spalten-Einstellungen',
    'userPrefsViewer.lastUpdated': 'Zuletzt aktualisiert',
    'userPrefsViewer.position': 'Position',
    'userPrefsViewer.visible': 'sichtbar',
    'userPrefsViewer.andMore': '... und {count} weitere Spalten',
    
    // DataHub
    'dataHub.title': 'Datenhub',
    'dataHub.description': 'Laden Sie Ihre Daten hoch und verwalten Sie Ihre Uploads',
    'dataHub.removeDuplicates': 'Duplikate entfernen',
    'dataHub.processing': 'Wird verarbeitet...',
    'dataHub.uploadXlsCsv': 'XLS/CSV hochladen',
    'dataHub.clearTable': 'Tabelle leeren',
    'dataHub.uploadHistory': 'Upload-Historie',
    'dataHub.uploadHistoryDesc': 'Übersicht Ihrer hochgeladenen Datensätze',
    'dataHub.deleteSelected': 'Ausgewählte löschen',
    'dataHub.filename': 'Dateiname',
    'dataHub.dataType': 'Datentyp',
    'dataHub.uploadDate': 'Upload-Datum',
    'dataHub.rowCount': 'Anzahl Zeilen',
    'dataHub.statusLabel': 'Status',
    'dataHub.statusSuccess': 'Erfolgreich',
    'dataHub.statusFailed': 'Fehlgeschlagen',
    'dataHub.noUploads': 'Keine Uploads vorhanden. Laden Sie Dateien hoch, um zu beginnen.',
    'dataHub.confirmDelete': 'Möchten Sie diesen Upload wirklich löschen?',
    'dataHub.confirmDeleteMultiple': 'Möchten Sie {count} Upload(s) wirklich löschen?',
    'dataHub.confirmClearTable': 'Tabelle leeren bestätigen',
    'dataHub.confirmClearTableDesc': 'Sind Sie sicher, dass Sie alle Einträge aus "{table}" löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'dataHub.clearing': 'Wird geleert...',
    'dataHub.clearTableButton': 'Tabelle leeren',
    'dataHub.noDuplicates': 'Keine Duplikate gefunden',
    'dataHub.duplicatesRemoved': '{count} Duplikate wurden erfolgreich entfernt',
    
    // Data Types
    'dataType.customer_projects': 'Kundenprojekte',
    'dataType.customer_projects_desc': 'Kunde, Projektname, Applikation, Produkt, Opportunity Creation Date',
    'dataType.customers': 'Kunden',
    'dataType.customers_desc': 'Kundenname, Branche, Land, Stadt, Kundenkategorie',
    'dataType.app_insights': 'App Insights',
    'dataType.app_insights_desc': 'Application, Application_Description, Application_BlockDiagram, Application_Trends, Industry, Product_Family_1-5',
    'dataType.applications': 'Applikationen',
    'dataType.applications_desc': 'Applikation, zugehöriges_Produkt',
    'dataType.products': 'Produkte',
    'dataType.products_desc': 'Produkt, Produktfamilie, Produktbeschreibung, Hersteller, Preis, Inventory, Lead_Time, Lifecycle, NPI, Top_Seller, Link_Herstellerseite',
    'dataType.cross_sells': 'Cross-Sells',
    'dataType.cross_sells_desc': 'Applikation, Basis_Produkt, Cross_Sell_Produkt, Rec_Source, Rec_Score',
    'dataType.product_alternatives': 'Produktalternativen',
    'dataType.product_alternatives_desc': 'Basis_Produkt, Alternatives_Produkt, Similarity',
    
    // Column Visibility
    'columns.title': 'Spalten',
    'columns.resetAll': 'Alle zurücksetzen',
    
    // Reports
    'reports.title': 'Reports',
    'reports.subtitle': 'Übersicht und Analyse Ihrer Geschäftsdaten',
    'reports.rejectedCrossSells': 'Abgelehnte Cross-Sells',
    'reports.rejectedCrossSellsDesc': 'Übersicht aller abgelehnten Cross-Sell Produkte',
    'reports.addedProducts': 'Ergänzte Produkte',
    'reports.addedProductsDesc': 'Alle zu Projekten hinzugefügten Cross-Sells und Alternativen',
    'reports.exportExcel': 'Excel exportieren',
    'reports.backToOverview': 'Zurück zur Übersicht',
    'reports.resetFilters': 'Filter zurücksetzen',
    'reports.restore': 'Wiederherstellen',
    'reports.rejectedProducts': 'Abgelehnte Produkte',
    'reports.addedEntries': 'Ergänzte Einträge',
    'reports.availableReports': 'Verfügbare Reports',
    'reports.selectReport': 'Wählen Sie einen Report aus den Karten aus',
    'reports.noRejectedCrossSells': 'Keine abgelehnten Cross-Sells vorhanden',
    'reports.noAddedProducts': 'Keine ergänzten Produkte vorhanden',
    'reports.removedProductsAppearHere': 'Produkte, die aus Cross-Sell Opportunities entfernt wurden, erscheinen hier',
    'reports.addCrossSellsOrAlternatives': 'Fügen Sie Cross-Sells oder Alternativen zu Projekten hinzu',
    'reports.entriesOf': '{filtered} von {total} Einträge',
    'reports.found': 'gefunden',
    'reports.allRejectedCrossSells': 'Alle abgelehnten Cross-Sells mit der Möglichkeit zur Wiederherstellung',
    'reports.allAddedProducts': 'Alle zu Projekten hinzugefügten Cross-Sells und Alternativen mit Validierungsstatus',
    'reports.searchRejected': 'Suche nach Produkt, Applikation, Projekt oder Grund...',
    'reports.searchAdded': 'Suche nach Kunde, Projekt, Produkt, Status...',
    'reports.allProductFamilies': 'Alle Produktfamilien',
    'reports.allRemovalReasons': 'Alle Ablehnungsgründe',
    'reports.allCustomers': 'Alle Kunden',
    'reports.allStatuses': 'Alle Status',
    'reports.allTypes': 'Alle Typen',
    'reports.allValidations': 'Alle Validierungen',
    'reports.noResults': 'Keine Ergebnisse gefunden',
    'reports.tryDifferentSearch': 'Versuchen Sie eine andere Suchanfrage',
    'reports.projectStatus': 'Projekt-Status',
    'reports.productType': 'Produkttyp',
    'reports.validationStatus': 'Validierungsstatus',
    'reports.dateAdded': 'Hinzugefügt',
    'reports.projectNumber': 'Projekt-Nr.',
    'reports.removalReason': 'Ablehnungsgrund',
    'reports.date': 'Datum',
    
    // Projects Detail
    'projects.back': 'Zurück',
    'projects.project': 'Projekt',
    'projects.projects': 'Projekte',
    'projects.close': 'Schließen',
    'projects.searchProjects': 'Projekte suchen...',
    'projects.searchCrossSells': 'Cross-Sells suchen...',
    'projects.productsInProject': 'Produkte im Projekt',
    'projects.crossSellOpportunities': 'Cross-Sell Opportunities',
    'projects.showAllCrossSells': 'Alle anzeigen',
    'projects.showAllCustomerProjects': 'Alle Projekte dieses Kunden anzeigen',
    'projects.applicationDetails': 'Applikationsdetails und Informationen',
    'projects.customerDetails': 'Kundendetails und Informationen',
    'projects.productDetails': 'Produktdetails und Spezifikationen',
    'projects.noDetailedInfo': 'Keine detaillierten Informationen verfügbar',
    'projects.noProductsInProject': 'Keine Produkte in diesem Projekt',
    'projects.noCrossSellsAvailable': 'Keine Cross-Sell Opportunities verfügbar',
    'projects.uploadProductsHint': 'Laden Sie Produktdaten im Datenhub hoch, um Empfehlungen zu erhalten',
    'projects.undoRemoval': 'Rückgängig machen',
    'projects.undoRemovalTitle': 'Entfernung rückgängig machen',
    'projects.undoRemovalDesc': 'Möchten Sie "{product}" wieder zu den Cross-Sell Opportunities hinzufügen?',
    'projects.confirmRemoval': 'Entfernung bestätigen',
    'projects.confirmRemovalDesc': 'Warum möchten Sie "{product}" aus den Cross-Sell Opportunities entfernen?',
    'projects.selectReason': 'Grund auswählen',
    'projects.confirm': 'Bestätigen',
    'projects.addedAsAlternative': '{product} als Alternative zum Projekt hinzugefügt',
    'projects.addedAsCrossSell': '{product} als Cross-Sell zum Projekt hinzugefügt',
    'projects.productRemoved': '{product} entfernt',
    'projects.statusUpdated': 'Projekt-Status auf "{status}" gesetzt',
    'projects.errorNotAuthenticated': 'Nicht authentifiziert',
    'projects.errorProjectNotFound': 'Projekt nicht gefunden',
    'projects.errorUpdatingStatus': 'Fehler beim Aktualisieren des Status',
    'projects.noProjectsFound': 'Keine Projekte gefunden',
    'projects.tryDifferentSearch': 'Versuchen Sie einen anderen Suchbegriff',
    'projects.uploadDataHint': 'Laden Sie Projektdaten im Datenhub hoch',
    'projects.crossSellsFor': 'Cross-Sells für',
    'projects.industry': 'Industrie',
    'projects.category': 'Kategorie',
    'projects.location': 'Standort',
    
    // Super Admin
    'superAdmin.title': 'Super Admin',
    'superAdmin.tabs.admins': 'Super-Admins',
    'superAdmin.tabs.tenants': 'Mandanten',
    'superAdmin.tabs.settings': 'Einstellungen',
    'superAdmin.management': 'Super-Admin Verwaltung',
    'superAdmin.managementDesc': 'Übersicht aller Super-Administratoren im System',
    'superAdmin.loading': 'Lädt...',
    'superAdmin.noAdmins': 'Keine Super-Administratoren gefunden',
    'superAdmin.name': 'Name',
    'superAdmin.email': 'E-Mail',
    'superAdmin.status': 'Status',
    'superAdmin.created': 'Erstellt',
    'superAdmin.actions': 'Aktionen',
    'superAdmin.noName': 'Kein Name',
    'superAdmin.you': 'Sie',
    'superAdmin.revokeRights': 'Rechte entziehen',
    'superAdmin.revokeTitle': 'Super-Admin Rechte entziehen?',
    'superAdmin.revokeDesc': 'Sind Sie sicher, dass Sie {name} die Super-Admin Rechte entziehen möchten?',
    'superAdmin.revokeWarning': 'Der Benutzer verliert alle administrativen Berechtigungen und kann nicht mehr auf die Super-Admin Funktionen zugreifen.',
    'superAdmin.cancel': 'Abbrechen',
    'superAdmin.revokeConfirm': 'Rechte entziehen',
    'superAdmin.total': 'Gesamt',
    'superAdmin.inviteNewAdmin': 'Neuen Super-Admin einladen',
    'superAdmin.inviting': 'Lädt ein...',
    'superAdmin.invite': 'Super-Admin einladen',
    'superAdmin.createTenant': 'Neuen Mandanten erstellen',
    'superAdmin.tenantName': 'Mandantenname',
    'superAdmin.creating': 'Erstelle...',
    'superAdmin.create': 'Erstellen',
    'superAdmin.allTenants': 'Alle Mandanten',
    'superAdmin.id': 'ID',
    'superAdmin.createdAt': 'Erstellt am',
    'superAdmin.management2': 'Verwaltung',
    'superAdmin.details': 'Details',
    'superAdmin.manageUsers': 'Benutzer verwalten',
    'superAdmin.inviteAdmin': 'Admin einladen',
    'superAdmin.noTenants': 'Noch keine Mandanten vorhanden',
    'superAdmin.loadError': 'Fehler beim Laden der Mandanten',
    'superAdmin.cleanupData': 'Globale Daten bereinigen',
    'superAdmin.cleanupDesc': 'Entfernt alle verwaisten Daten ohne Mandantenzuordnung (tenant_id = NULL) aus der Datenbank. Diese Aktion kann nicht rückgängig gemacht werden.',
    'superAdmin.cleaning': 'Bereinige...',
    'superAdmin.cleanupButton': 'Globale Daten löschen',
    'superAdmin.inviteTenantAdmin': 'Tenant-Admin einladen',
    'superAdmin.inviteTenantAdminDesc': 'Laden Sie einen Administrator für den Mandanten "{tenant}" ein. Der eingeladene Benutzer erhält Admin-Rechte für diesen Mandanten.',
    'superAdmin.emailAddress': 'E-Mail-Adresse',
    'superAdmin.sendInvite': 'Einladung senden',
    'superAdmin.editTenant': 'Mandant bearbeiten',
    'superAdmin.editTenantDesc': 'Ändern Sie den Namen des Mandanten "{tenant}".',
    'superAdmin.companyName': 'Firmenname',
    'superAdmin.saving': 'Speichert...',
    'superAdmin.save': 'Speichern',
    'superAdmin.deleteTenant': 'Mandant wirklich löschen?',
    'superAdmin.deleteTenantDesc': 'Möchten Sie den Mandanten "{tenant}" wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden und alle zugehörigen Daten werden ebenfalls gelöscht.',
    'superAdmin.deleting': 'Löscht...',
    'superAdmin.delete': 'Löschen',
    'superAdmin.usersAndRoles': 'Benutzer und deren Rollen in diesem Mandanten',
    'superAdmin.addUser': 'Benutzer hinzufügen',
    'superAdmin.addUserHint': 'Geben Sie die E-Mail-Adresse eines existierenden Benutzers ein, um ihn diesem Mandanten zuzuweisen.',
    'superAdmin.adding': 'Lädt...',
    'superAdmin.add': 'Hinzufügen',
    'superAdmin.role': 'Rolle',
    'superAdmin.roleUser': 'User',
    'superAdmin.roleTenantAdmin': 'Tenant Admin',
    'superAdmin.noUsers': 'Keine Benutzer in diesem Mandanten',
    
    // Access Logs
    'accessLogs.title': 'Zugriffsprotokolle',
    'accessLogs.noPermission': 'Keine Berechtigung',
    'accessLogs.totalEvents': 'Gesamt Events',
    'accessLogs.logins': 'Logins',
    'accessLogs.logouts': 'Logouts',
    'accessLogs.pageViews': 'Seitenaufrufe',
    'accessLogs.actions': 'Aktionen',
    'accessLogs.uniqueUsers': 'Aktive Benutzer',
    'accessLogs.userAccessTracking': 'User Access Tracking',
    'accessLogs.filter': 'Filter',
    'accessLogs.excelExport': 'Excel Export',
    'accessLogs.eventType': 'Event-Typ',
    'accessLogs.all': 'Alle',
    'accessLogs.login': 'Login',
    'accessLogs.logout': 'Logout',
    'accessLogs.pageView': 'Seitenaufruf',
    'accessLogs.action': 'Aktion',
    'accessLogs.user': 'Benutzer',
    'accessLogs.userPlaceholder': 'Name oder E-Mail...',
    'accessLogs.fromDate': 'Von Datum',
    'accessLogs.toDate': 'Bis Datum',
    'accessLogs.resetFilters': 'Filter zurücksetzen',
    'accessLogs.entries': 'Einträge',
    'accessLogs.entry': 'Eintrag',
    'accessLogs.of': 'von',
    'accessLogs.total': 'gesamt',
    'accessLogs.timestamp': 'Zeitstempel',
    'accessLogs.event': 'Event',
    'accessLogs.page': 'Seite',
    'accessLogs.userAgent': 'User Agent',
    'accessLogs.noEntries': 'Keine Einträge gefunden',
    'accessLogs.noLogs': 'Keine Access Logs vorhanden',
    'accessLogs.unknown': 'Unbekannt',
    'accessLogs.exported': 'Einträge exportiert',
    'accessLogs.exportError': 'Fehler beim Excel-Export',
    'accessLogs.loadError': 'Fehler beim Laden der Access Logs',
  },
  en: {
    // Navigation
    'nav.cockpit': 'Cockpit',
    'nav.projects': 'Projects',
    'nav.products': 'Products',
    'nav.customers': 'Customers',
    'nav.collections': 'Collections',
    'nav.reports': 'Reports',
    'nav.administration': 'Administration',
    'nav.admin': 'Admin',
    'nav.dataHub': 'Data Hub',
    'nav.logout': 'Logout',
    'nav.applications': 'Applications',
    'nav.superAdmin': 'Super Admin',
    'nav.accessLogs': 'Access Logs',
    'nav.utility': 'Utility',
    
    // Page Titles
    'page.projects': 'Projects',
    'page.products': 'Products',
    'page.customers': 'Customers',
    'page.collections': 'Collections',
    'page.applications': 'Applications',
    'page.admin': 'Admin',
    'page.reports': 'Reports',
    'page.dataHub': 'Data Hub',
    'page.superAdmin': 'Super Admin',
    'page.dashboard': 'Dashboard',
    'page.settings': 'Settings',
    'page.crossSells': 'Cross Sells',
    
    // Search
    'search.placeholder': 'Search for projects, products, customers...',
    'search.noResults': 'No results found',
    'search.projects': 'Projects',
    'search.products': 'Products',
    'search.customers': 'Customers',
    'search.applications': 'Applications',
    'search.collections': 'Collections',
    'search.searchProjects': 'Search projects...',
    'search.searchProducts': 'Search products...',
    'search.searchCustomers': 'Search customers...',
    'search.searchApplications': 'Search applications...',
    'search.searchCrossSells': 'Search cross-sells...',
    'search.searchCollections': 'Search collections...',
    
    // User Preferences
    'userPrefs.title': 'User Preferences',
    'userPrefs.theme': 'Theme',
    'userPrefs.light': 'Light',
    'userPrefs.dark': 'Dark',
    'userPrefs.system': 'System',
    'userPrefs.language': 'Language',
    
    // Preferences Popover
    'prefs.title': 'User Preferences',
    'prefs.subtitle': 'Customize your content and display settings.',
    'prefs.content': 'Content',
    'prefs.view': 'View',
    'prefs.functions': 'Functions',
    'prefs.targetApplications': 'Target Applications',
    'prefs.productFamilies': 'Product Families',
    'prefs.manufacturers': 'Manufacturers',
    'prefs.none': 'None',
    'prefs.saved': 'Preferences saved',
    'prefs.saveError': 'Error saving preferences',
    'prefs.saving': 'Saving...',
    'prefs.recentProjectsCount': 'Number of "Recent" Projects',
    'prefs.recentProjectsDesc': 'How many recently viewed projects should be displayed?',
    'prefs.selectCount': 'Select count',
    'prefs.projects': 'Projects',
    'prefs.autoLogoffTime': 'Auto-Logoff Time',
    'prefs.autoLogoffDesc': 'After how many minutes of inactivity should you be automatically logged out?',
    'prefs.selectTime': 'Select time',
    'prefs.minutes': 'Minutes',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.noNotifications': 'No notifications',
    'notifications.showsLast7Days': 'Shows activities from the last 7 days',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.statistics': 'Statistics',
    'dashboard.recentProjects': 'Recent Projects',
    'dashboard.actionItems': 'Action Items',
    'dashboard.gettingStarted': 'Getting Started',
    
    // Widget Settings
    'widgetSettings.customize': 'Customize Dashboard',
    'widgetSettings.customizeWidgets': 'Customize Widgets',
    'widgetSettings.customizeDesc': 'Choose which widgets to display. Drag them to change the order.',
    'widgetSettings.projects': 'Projects',
    'widgetSettings.actionItems': 'Action Items',
    'widgetSettings.npiProducts': 'NPI Products',
    'widgetSettings.statistics': 'Statistics',
    'widgetSettings.optimizationStatus': 'Optimization Status',
    'widgetSettings.loginActivity': 'Login Activity (Admin)',
    'widgetSettings.accessStats': 'Access Statistics (Admin)',
    'widgetSettings.addedProducts': 'Added Products',
    'widgetSettings.gettingStarted': 'Getting Started',
    'widgetSettings.halfWidth': 'Half Width',
    'widgetSettings.fullWidth': 'Full Width',
    
    // Common Actions
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.configure': 'Configure',
    'common.reset': 'Reset',
    'common.showAll': 'Show all',
    'common.show': 'Show',
    'common.hide': 'Hide',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.reject': 'Reject',
    'common.details': 'Details',
    'common.actions': 'Actions',
    'common.noData': 'No data available',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Table Headers - Projects
    'table.projectName': 'Project Name',
    'table.customer': 'Customer',
    'table.application': 'Application',
    'table.applications': 'Applications',
    'table.product': 'Product',
    'table.products': 'Products',
    'table.status': 'Status',
    'table.optimizationStatus': 'Optimization Status',
    'table.created': 'Created',
    'table.lastModified': 'Last Modified',
    'table.productsInProject': 'Products in Project',
    'table.crossSellOpportunities': 'Cross-Sell Opportunities',
    
    // Table Headers - Products
    'table.component': 'Component',
    'table.manufacturer': 'Manufacturer',
    'table.productFamily': 'Product Family',
    'table.description': 'Description',
    'table.tags': 'Tags',
    'table.price': 'Price',
    'table.priceTooltip': 'in €/pcs',
    'table.leadTime': 'Lead Time',
    'table.leadTimeTooltip': 'in weeks',
    'table.inventory': 'Inventory',
    'table.inventoryTooltip': 'in pcs',
    'table.crossSells': 'Cross-Sells',
    'table.link': 'Link',
    'table.alternatives': 'Alternatives',
    'table.reason': 'Reason',
    'table.score': 'Score',
    'table.recommendation': 'Recommendation',
    'table.action': 'Action',
    
    // Table Headers - Customers
    'table.customerName': 'Customer',
    'table.industry': 'Industry',
    'table.country': 'Country',
    'table.city': 'City',
    'table.category': 'Category',
    'table.projectCount': 'Projects',
    
    // Optimization Status
    'status.new': 'New',
    'status.open': 'Open',
    'status.review': 'Review',
    'status.validation': 'Validation',
    'status.completed': 'Completed',
    'status.identified': 'Identified',
    'status.suggested': 'Suggested',
    'status.accepted': 'Accepted',
    'status.registered': 'Registered',
    'status.rejected': 'Rejected',
    
    // Filter Options
    'filter.all': 'All',
    'filter.allProjects': 'All Projects',
    'filter.allProducts': 'All Products',
    'filter.allCustomers': 'All Customers',
    'filter.allApplications': 'All Applications',
    'filter.allCategories': 'All Categories',
    'filter.allIndustries': 'All Industries',
    'filter.allCountries': 'All Countries',
    'filter.allCities': 'All Cities',
    'filter.favorites': 'Favorites',
    'filter.recent': 'Recent',
    'filter.status': 'Status',
    'filter.productFamily': 'Product Family',
    'filter.manufacturer': 'Manufacturer',
    'filter.lifecycle': 'Lifecycle',
    'filter.npiOnly': 'NPI Only',
    'filter.topOnly': 'Top Only',
    
    // Pagination
    'pagination.results': 'Results',
    'pagination.resultsPerPage': 'Results per page',
    'pagination.of': 'of',
    'pagination.previous': 'Previous',
    'pagination.next': 'Next',
    'pagination.page': 'Page',
    
    // Dashboard Widgets
    'widget.projects': 'Projects',
    'widget.statistics': 'Statistics',
    'widget.actionItems': 'Action Items',
    'widget.gettingStarted': 'Getting Started',
    'widget.optimizationStatus': 'Projects by Optimization Status',
    'widget.npiProducts': 'NPI Products',
    'widget.addedProducts': 'Added Products',
    'widget.loginActivity': 'Login Activity',
    'widget.accessStats': 'Access Statistics',
    'widget.search': 'Search',
    
    // NPI Products Widget
    'npiProducts.title': 'NPI Products',
    'npiProducts.noProducts': 'No NPI products available',
    
    // Project Detail
    'project.metadata': 'Project Details',
    'project.createdAt': 'Created',
    'project.customer': 'Customer',
    'project.application': 'Application',
    'project.products': 'Products',
    'project.crossSells': 'Cross-Sells',
    'project.alternatives': 'Alternatives',
    'project.noProducts': 'No products in this project',
    'project.noCrossSells': 'No cross-sell opportunities available',
    'project.addProduct': 'Add product',
    'project.removeProduct': 'Remove product',
    
    // Product Detail
    'product.details': 'Product Details',
    'product.addToCollection': 'Add to collection',
    'product.selectCollection': 'Select collection',
    'product.createCollection': 'Create new collection',
    'product.collectionName': 'Collection name',
    'product.collectionCreated': 'Collection created',
    'product.addedToCollection': 'Product added to collection',
    'product.alreadyInCollection': 'Product is already in this collection',
    
    // Customer Detail
    'customer.details': 'Customer Details',
    'customer.location': 'Location',
    'customer.viewProjects': 'View projects',
    
    // Dialogs
    'dialog.confirmDelete': 'Confirm Delete',
    'dialog.deleteMessage': 'Are you sure you want to delete this entry?',
    'dialog.inviteUser': 'Invite User',
    'dialog.addToCollection': 'Add to Collection',
    'dialog.removeReason': 'Reason for removal',
    
    // Toast Messages
    'toast.success': 'Success',
    'toast.error': 'Error',
    'toast.saved': 'Saved',
    'toast.deleted': 'Deleted',
    'toast.added': 'Added',
    'toast.removed': 'Removed',
    'toast.updated': 'Updated',
    'toast.loadError': 'Error loading data',
    'toast.saveError': 'Error saving data',
    'toast.deleteError': 'Error deleting data',
    
    // Admin
    'admin.users': 'Users',
    'admin.inviteUser': 'Invite User',
    'admin.role': 'Role',
    'admin.lastLogin': 'Last Login',
    'admin.pendingInvitation': 'Pending Invitation',
    'admin.deleteUser': 'Delete User',
    'admin.userManagement': 'User Management',
    
    // Removal Reasons
    'removal.technicalFit': 'Technical Fit',
    'removal.commercialFit': 'Commercial Fit',
    'removal.otherSupplier': 'Other Supplier',
    'removal.noNeed': 'No Need',
    'removal.other': 'Other',
    
    // Product Lifecycle
    'lifecycle.comingSoon': 'Coming Soon',
    'lifecycle.active': 'Active',
    'lifecycle.nfnd': 'NFND',
    'lifecycle.discontinued': 'Discontinued',
    
    // Empty States
    'empty.projects': 'No projects found',
    'empty.products': 'No products found',
    'empty.customers': 'No customers found',
    'empty.collections': 'No collections found',
    'empty.applications': 'No applications found',
    'empty.crossSells': 'No cross-sells available',
    'empty.alternatives': 'No alternatives available',
    
    // Column Visibility
    'columns.configure': 'Configure columns',
    'columns.reset': 'Reset',
    'columns.showAll': 'Show all',
    'columns.hideAll': 'Hide all',
    
    // Quick Filters - Projects
    'quickFilter.all': 'All',
    'quickFilter.favorites': 'Favorites',
    'quickFilter.recent': 'Recent',
    'quickFilter.new': 'New',
    'quickFilter.review': 'Review',
    
    // Collections
    'collections.title': 'Collections',
    'collections.new': 'New Collection',
    'collections.edit': 'Edit Collection',
    'collections.create': 'Create New Collection',
    'collections.name': 'Name',
    'collections.description': 'Description (optional)',
    'collections.visibility': 'Visibility',
    'collections.visibilityPrivate': 'Only me',
    'collections.visibilitySelected': 'Selected users',
    'collections.visibilityOrganization': 'Entire organization',
    'collections.shareWith': 'Share with users',
    'collections.selectUser': 'Select user...',
    'collections.products': 'Products',
    'collections.createdBy': 'Created by',
    'collections.noCollections': 'No collections yet',
    'collections.noProducts': 'This collection contains no products',
    'collections.confirmDelete': 'Really delete collection?',
    'collections.updated': 'Collection updated',
    'collections.created': 'Collection created',
    'collections.deleted': 'Collection deleted',
    'collections.productRemoved': 'Product removed',
    'collections.saveError': 'Error saving',
    'collections.selectProducts': 'Select products',
    
    // Applications
    'applications.title': 'Applications',
    'applications.relatedProduct': 'Related Product',
    'applications.noApplications': 'No applications found',
    'applications.tryDifferentSearch': 'Try a different search term',
    'applications.startUpload': 'Start by uploading application data',
    'applications.details': 'Application details and information',
    'applications.industry': 'Industry',
    'applications.trends': 'Trends',
    'applications.productFamilies': 'Product Families',
    'applications.blockDiagram': 'Block Diagram',
    'applications.noDetails': 'No detailed information available for this application.',
    
    // Action Items
    'actionItems.title': 'Action Items',
    'actionItems.new': 'New',
    'actionItems.edit': 'Edit Action Item',
    'actionItems.create': 'New Action Item',
    'actionItems.titleLabel': 'Title',
    'actionItems.titlePlaceholder': 'Action item title',
    'actionItems.descriptionLabel': 'Description',
    'actionItems.descriptionPlaceholder': 'Optional description',
    'actionItems.priority': 'Priority',
    'actionItems.priorityLow': 'Low',
    'actionItems.priorityMedium': 'Medium',
    'actionItems.priorityHigh': 'High',
    'actionItems.statusOpen': 'Open',
    'actionItems.statusInProgress': 'In Progress',
    'actionItems.statusCompleted': 'Completed',
    'actionItems.assignedTo': 'Assigned to',
    'actionItems.assignMyself': 'Myself',
    'actionItems.assignment': 'Assignment (optional)',
    'actionItems.project': 'Project',
    'actionItems.customer': 'Customer',
    'actionItems.selectProject': 'Select project...',
    'actionItems.selectCustomer': 'Select customer...',
    'actionItems.dueDate': 'Due date (optional)',
    'actionItems.noItems': 'No action items yet. Create your first one!',
    'actionItems.sortByCreation': 'By creation',
    'actionItems.sortByPriority': 'By priority',
    'actionItems.sortByDueDate': 'By due date',
    'actionItems.updated': 'Action item updated',
    'actionItems.created': 'Action item created',
    'actionItems.deleted': 'Action item deleted',
    'actionItems.saveError': 'Error saving',
    
    // Search Widget
    'searchWidget.title': 'Opportunity Optimizer',
    'searchWidget.subtitle': 'Find cross-selling and up-selling potential in your customer projects',
    'searchWidget.placeholder': 'Search for customers, projects, applications or products...',
    'searchWidget.searching': 'Searching for',
    'searchWidget.noResults': 'No results found. Upload data in the Data Hub to get started.',
    'searchWidget.recentlyViewed': 'Recently viewed',
    'searchWidget.crossSellOpportunities': 'Cross-Selling Opportunities',
    
    // Statistics Widget
    'statistics.projects': 'Projects',
    'statistics.products': 'Products',
    'statistics.crossSelling': 'Cross-Selling',
    'statistics.inDatabase': 'In database',
    'statistics.available': 'Available',
    'statistics.opportunities': 'Opportunities',
    'statistics.projectOverview': 'Project Overview',
    'statistics.allActiveProjects': 'All active customer projects in database',
    'statistics.productCatalog': 'Product Catalog',
    'statistics.allAvailableProducts': 'All available products for optimizations',
    'statistics.crossSellingPotential': 'Cross-Selling Potential',
    'statistics.identifiedOpportunities': 'Identified sales opportunities for additional products',
    
    // Optimization Status Widget
    'optimizationStatus.title': 'Projects by Optimization Status',
    'optimizationStatus.allTenants': 'All Tenants',
    'optimizationStatus.aggregatedDistribution': 'Aggregated distribution of all projects from all tenants by status',
    'optimizationStatus.distribution': 'Distribution of projects by status in selected time frame',
    'optimizationStatus.total': 'Total',
    'optimizationStatus.totalAllTenants': 'Total (All Tenants)',
    'optimizationStatus.projects': 'Projects',
    'optimizationStatus.projectsCrossTenants': 'Projects across tenants',
    'optimizationStatus.noProjectsInTenants': 'No projects found in tenants',
    'optimizationStatus.noProjectsInTimeframe': 'No projects in selected time frame',
    'optimizationStatus.ensureTenantsHaveData': 'Make sure tenants have uploaded project data',
    'optimizationStatus.tryLongerTimeframe': 'Try a longer time frame or upload project data',
    'optimizationStatus.distributionByStatus': 'Distribution by status',
    'optimizationStatus.projectCount': 'Number of projects',
    'optimizationStatus.1month': '1 month',
    'optimizationStatus.3months': '3 months',
    'optimizationStatus.6months': '6 months',
    'optimizationStatus.12months': '12 months',
    
    // Added Products Widget
    'addedProducts.title': 'Added Products by Status',
    'addedProducts.description': 'Cross-sells and alternatives added to projects',
    'addedProducts.noProducts': 'No added products in selected time frame',
    'addedProducts.addProductsHint': 'Add cross-sells or alternatives to projects to see them here',
    'addedProducts.total': 'Total',
    'addedProducts.crossSells': 'Cross-Sells',
    'addedProducts.alternatives': 'Alternatives',
    'addedProducts.distributionByStatus': 'Distribution by status',
    'addedProducts.1month': '1 month',
    'addedProducts.3months': '3 months',
    'addedProducts.6months': '6 months',
    'addedProducts.12months': '12 months',
    
    // Login Activity Widget
    'loginActivity.title': 'Login Activity',
    'loginActivity.description': 'Login history in selected time frame',
    'loginActivity.totalLogins': 'Total Logins',
    'loginActivity.activeUsers': 'Active Users',
    'loginActivity.avgLoginsPerUser': 'Avg Logins/User',
    'loginActivity.avgLoginsPerDay': 'Avg Logins/Day',
    'loginActivity.logins': 'Logins',
    'loginActivity.timeRange': 'Time Range',
    'loginActivity.granularity': 'Granularity',
    'loginActivity.daily': 'Daily',
    'loginActivity.weekly': 'Weekly',
    'loginActivity.monthly': 'Monthly',
    'loginActivity.week': 'Week',
    'loginActivity.1month': '1 month',
    'loginActivity.3months': '3 months',
    'loginActivity.6months': '6 months',
    'loginActivity.12months': '12 months',
    
    // Access Stats Widget
    'accessStats.title': 'Access Statistics',
    'accessStats.description': 'User activities in selected time frame',
    'accessStats.totalEvents': 'Total Events',
    'accessStats.activeUsers': 'Active Users',
    'accessStats.avgEventsPerUser': 'Avg Events/User',
    'accessStats.count': 'Count',
    'accessStats.timeRange': 'Time Range',
    'accessStats.logins': 'Logins',
    'accessStats.logouts': 'Logouts',
    'accessStats.pageViews': 'Page Views',
    'accessStats.actions': 'Actions',
    'accessStats.1month': '1 month',
    'accessStats.3months': '3 months',
    'accessStats.6months': '6 months',
    'accessStats.12months': '12 months',
    
    // Getting Started Widget
    'gettingStarted.title': 'Getting Started',
    'gettingStarted.step1Title': 'Upload Data',
    'gettingStarted.step1Description': 'Start by uploading your customer projects and product data in the Data Hub',
    'gettingStarted.step2Title': 'Browse Data',
    'gettingStarted.step2Description': 'Use search to find cross-selling and alternative product recommendations',
    'gettingStarted.step3Title': 'Leverage Sales Opportunities',
    'gettingStarted.step3Description': 'Analyze the suggestions and contact your customers with new offers',
    
    // Product Status
    'productStatus.identified': 'Identified',
    'productStatus.suggested': 'Suggested',
    'productStatus.accepted': 'Accepted',
    'productStatus.registered': 'Registered',
    'productStatus.rejected': 'Rejected',
    
    // Projects Widget
    'projectsWidget.showAll': 'Show all {count} projects',
    'projectsWidget.noProjects': 'No projects found',
    'projectsWidget.customer': 'Customer',
    'projectsWidget.application': 'Application',
    'projectsWidget.created': 'Created',
    'projectsWidget.modified': 'Modified',
    'projectsWidget.status': 'Status',
    
    // Admin Page
    'admin.title': 'User Management',
    'admin.description': 'Manage users, their roles and settings',
    'admin.usersTab': 'Users',
    'admin.preferencesTab': 'User Preferences',
    'admin.inviteButton': 'Invite User',
    'admin.inviteDialogTitle': 'Invite New User',
    'admin.inviteDialogDesc': 'Send an invitation email to a new user',
    'admin.firstName': 'First Name',
    'admin.lastName': 'Last Name',
    'admin.email': 'Email Address',
    'admin.roleLabel': 'Role',
    'admin.roleUser': 'User',
    'admin.roleTenantAdmin': 'Tenant Admin',
    'admin.registeredUsers': 'Already registered users',
    'admin.registeredUsersHint': 'These email addresses are already registered',
    'admin.sendInvite': 'Send Invitation',
    'admin.sending': 'Sending...',
    'admin.totalUsers': 'Total Users',
    'admin.registeredUsersCount': 'Registered users',
    'admin.admins': 'Administrators',
    'admin.adminsCount': 'With admin rights',
    'admin.recentActivity': 'Recently Active',
    'admin.lastDays': 'Last 7 days',
    'admin.searchUsers': 'Search users...',
    'admin.name': 'Name',
    'admin.registered': 'Registered',
    'admin.noUsers': 'No users found',
    'admin.resendInvite': 'Resend Invitation',
    'admin.resendInviteShort': 'Invitation',
    'admin.makeAdmin': 'Make Admin',
    'admin.removeAdmin': 'Remove Admin',
    'admin.roleAdmin': 'Admin',
    'admin.confirmDeleteTitle': 'Delete User',
    'admin.confirmDeleteDesc': 'Are you sure you want to delete the user "{email}"? This action cannot be undone.',
    'admin.deleting': 'Deleting...',
    'admin.noTenantSelected': 'No tenant selected. Please select a tenant from the sidebar.',
    'admin.backToSuperAdmin': 'Back to Super Admin Dashboard',
    'admin.activeUsers': 'Active Users',
    'admin.last30Days': 'Last 30 days',
    'admin.allUsers': 'All Users',
    'admin.manageUsersPermissions': 'Manage users and their permissions',
    'admin.searchByEmailOrName': 'Search by email or name...',
    'admin.actionsColumn': 'Actions',
    'admin.noUsersFoundFor': 'No users found for',
    'admin.noUsersAvailable': 'No users available',
    'admin.deleteUserTitle': 'Delete User?',
    'admin.deleteUserConfirm': 'Are you sure you want to delete the user?',
    'admin.deleteUserWarning': 'This action cannot be undone. All user data will be permanently deleted.',
    
    // User Preferences Viewer
    'userPrefsViewer.title': 'User Settings',
    'userPrefsViewer.description': 'Overview of all user preferences in the tenant',
    'userPrefsViewer.usersWithDashboard': 'Users with Dashboard Settings',
    'userPrefsViewer.usersWithColumns': 'Users with Column Settings',
    'userPrefsViewer.ofUsers': 'of {count} users',
    'userPrefsViewer.totalSettings': 'Total Settings',
    'userPrefsViewer.configurations': 'Configurations',
    'userPrefsViewer.userOverview': 'User Overview',
    'userPrefsViewer.userOverviewDesc': 'Dashboard and column settings per user',
    'userPrefsViewer.dashboard': 'Dashboard',
    'userPrefsViewer.columns': 'Columns',
    'userPrefsViewer.noDashboardSettings': 'No dashboard settings',
    'userPrefsViewer.noColumnSettings': 'No column settings',
    'userPrefsViewer.lastUpdated': 'Last updated',
    'userPrefsViewer.position': 'Position',
    'userPrefsViewer.visible': 'visible',
    'userPrefsViewer.andMore': '... and {count} more columns',
    
    // DataHub
    'dataHub.title': 'Data Hub',
    'dataHub.description': 'Upload your data and manage your uploads',
    'dataHub.removeDuplicates': 'Remove Duplicates',
    'dataHub.processing': 'Processing...',
    'dataHub.uploadXlsCsv': 'Upload XLS/CSV',
    'dataHub.clearTable': 'Clear Table',
    'dataHub.uploadHistory': 'Upload History',
    'dataHub.uploadHistoryDesc': 'Overview of your uploaded datasets',
    'dataHub.deleteSelected': 'Delete Selected',
    'dataHub.filename': 'Filename',
    'dataHub.dataType': 'Data Type',
    'dataHub.uploadDate': 'Upload Date',
    'dataHub.rowCount': 'Row Count',
    'dataHub.statusLabel': 'Status',
    'dataHub.statusSuccess': 'Success',
    'dataHub.statusFailed': 'Failed',
    'dataHub.noUploads': 'No uploads yet. Upload files to get started.',
    'dataHub.confirmDelete': 'Do you really want to delete this upload?',
    'dataHub.confirmDeleteMultiple': 'Do you really want to delete {count} upload(s)?',
    'dataHub.confirmClearTable': 'Confirm Clear Table',
    'dataHub.confirmClearTableDesc': 'Are you sure you want to delete all entries from "{table}"? This action cannot be undone.',
    'dataHub.clearing': 'Clearing...',
    'dataHub.clearTableButton': 'Clear Table',
    'dataHub.noDuplicates': 'No duplicates found',
    'dataHub.duplicatesRemoved': '{count} duplicates were successfully removed',
    
    // Data Types
    'dataType.customer_projects': 'Customer Projects',
    'dataType.customer_projects_desc': 'Customer, Project Name, Application, Product, Opportunity Creation Date',
    'dataType.customers': 'Customers',
    'dataType.customers_desc': 'Customer Name, Industry, Country, City, Customer Category',
    'dataType.app_insights': 'App Insights',
    'dataType.app_insights_desc': 'Application, Application_Description, Application_BlockDiagram, Application_Trends, Industry, Product_Family_1-5',
    'dataType.applications': 'Applications',
    'dataType.applications_desc': 'Application, Related_Product',
    'dataType.products': 'Products',
    'dataType.products_desc': 'Product, Product Family, Product Description, Manufacturer, Price, Inventory, Lead_Time, Lifecycle, NPI, Top_Seller, Manufacturer_Link',
    'dataType.cross_sells': 'Cross-Sells',
    'dataType.cross_sells_desc': 'Application, Base_Product, Cross_Sell_Product, Rec_Source, Rec_Score',
    'dataType.product_alternatives': 'Product Alternatives',
    'dataType.product_alternatives_desc': 'Base_Product, Alternative_Product, Similarity',
    
    // Column Visibility
    'columns.title': 'Columns',
    'columns.resetAll': 'Reset All',
    
    // Reports
    'reports.title': 'Reports',
    'reports.subtitle': 'Overview and analysis of your business data',
    'reports.rejectedCrossSells': 'Rejected Cross-Sells',
    'reports.rejectedCrossSellsDesc': 'Overview of all rejected cross-sell products',
    'reports.addedProducts': 'Added Products',
    'reports.addedProductsDesc': 'All cross-sells and alternatives added to projects',
    'reports.exportExcel': 'Export Excel',
    'reports.backToOverview': 'Back to Overview',
    'reports.resetFilters': 'Reset Filters',
    'reports.restore': 'Restore',
    'reports.rejectedProducts': 'Rejected Products',
    'reports.addedEntries': 'Added Entries',
    'reports.availableReports': 'Available Reports',
    'reports.selectReport': 'Select a report from the cards above',
    'reports.noRejectedCrossSells': 'No rejected cross-sells available',
    'reports.noAddedProducts': 'No added products available',
    'reports.removedProductsAppearHere': 'Products removed from cross-sell opportunities will appear here',
    'reports.addCrossSellsOrAlternatives': 'Add cross-sells or alternatives to projects',
    'reports.entriesOf': '{filtered} of {total} entries',
    'reports.found': 'found',
    'reports.allRejectedCrossSells': 'All rejected cross-sells with option to restore',
    'reports.allAddedProducts': 'All cross-sells and alternatives added to projects with validation status',
    'reports.searchRejected': 'Search by product, application, project or reason...',
    'reports.searchAdded': 'Search by customer, project, product, status...',
    'reports.allProductFamilies': 'All Product Families',
    'reports.allRemovalReasons': 'All Removal Reasons',
    'reports.allCustomers': 'All Customers',
    'reports.allStatuses': 'All Statuses',
    'reports.allTypes': 'All Types',
    'reports.allValidations': 'All Validations',
    'reports.noResults': 'No results found',
    'reports.tryDifferentSearch': 'Try a different search query',
    'reports.projectStatus': 'Project Status',
    'reports.productType': 'Product Type',
    'reports.validationStatus': 'Validation Status',
    'reports.dateAdded': 'Date Added',
    'reports.projectNumber': 'Project No.',
    'reports.removalReason': 'Removal Reason',
    'reports.date': 'Date',
    
    // Projects Detail
    'projects.back': 'Back',
    'projects.project': 'Project',
    'projects.projects': 'Projects',
    'projects.close': 'Close',
    'projects.searchProjects': 'Search projects...',
    'projects.searchCrossSells': 'Search cross-sells...',
    'projects.productsInProject': 'Products in Project',
    'projects.crossSellOpportunities': 'Cross-Sell Opportunities',
    'projects.showAllCrossSells': 'Show All',
    'projects.showAllCustomerProjects': 'Show all projects for this customer',
    'projects.applicationDetails': 'Application details and information',
    'projects.customerDetails': 'Customer details and information',
    'projects.productDetails': 'Product details and specifications',
    'projects.noDetailedInfo': 'No detailed information available',
    'projects.noProductsInProject': 'No products in this project',
    'projects.noCrossSellsAvailable': 'No cross-sell opportunities available',
    'projects.uploadProductsHint': 'Upload product data in the Data Hub to receive recommendations',
    'projects.undoRemoval': 'Undo',
    'projects.undoRemovalTitle': 'Undo Removal',
    'projects.undoRemovalDesc': 'Do you want to add "{product}" back to the cross-sell opportunities?',
    'projects.confirmRemoval': 'Confirm Removal',
    'projects.confirmRemovalDesc': 'Why do you want to remove "{product}" from cross-sell opportunities?',
    'projects.selectReason': 'Select reason',
    'projects.confirm': 'Confirm',
    'projects.addedAsAlternative': '{product} added as alternative to project',
    'projects.addedAsCrossSell': '{product} added as cross-sell to project',
    'projects.productRemoved': '{product} removed',
    'projects.statusUpdated': 'Project status set to "{status}"',
    'projects.errorNotAuthenticated': 'Not authenticated',
    'projects.errorProjectNotFound': 'Project not found',
    'projects.errorUpdatingStatus': 'Error updating status',
    'projects.noProjectsFound': 'No projects found',
    'projects.tryDifferentSearch': 'Try a different search term',
    'projects.uploadDataHint': 'Upload project data in the Data Hub',
    'projects.crossSellsFor': 'Cross-Sells for',
    'projects.industry': 'Industry',
    'projects.category': 'Category',
    'projects.location': 'Location',
    
    // Super Admin
    'superAdmin.title': 'Super Admin',
    'superAdmin.tabs.admins': 'Super Admins',
    'superAdmin.tabs.tenants': 'Tenants',
    'superAdmin.tabs.settings': 'Settings',
    'superAdmin.management': 'Super Admin Management',
    'superAdmin.managementDesc': 'Overview of all super administrators in the system',
    'superAdmin.loading': 'Loading...',
    'superAdmin.noAdmins': 'No super administrators found',
    'superAdmin.name': 'Name',
    'superAdmin.email': 'Email',
    'superAdmin.status': 'Status',
    'superAdmin.created': 'Created',
    'superAdmin.actions': 'Actions',
    'superAdmin.noName': 'No name',
    'superAdmin.you': 'You',
    'superAdmin.revokeRights': 'Revoke rights',
    'superAdmin.revokeTitle': 'Revoke Super Admin rights?',
    'superAdmin.revokeDesc': 'Are you sure you want to revoke super admin rights from {name}?',
    'superAdmin.revokeWarning': 'The user will lose all administrative permissions and will no longer be able to access super admin functions.',
    'superAdmin.cancel': 'Cancel',
    'superAdmin.revokeConfirm': 'Revoke rights',
    'superAdmin.total': 'Total',
    'superAdmin.inviteNewAdmin': 'Invite new Super Admin',
    'superAdmin.inviting': 'Inviting...',
    'superAdmin.invite': 'Invite Super Admin',
    'superAdmin.createTenant': 'Create new tenant',
    'superAdmin.tenantName': 'Tenant name',
    'superAdmin.creating': 'Creating...',
    'superAdmin.create': 'Create',
    'superAdmin.allTenants': 'All Tenants',
    'superAdmin.id': 'ID',
    'superAdmin.createdAt': 'Created at',
    'superAdmin.management2': 'Management',
    'superAdmin.details': 'Details',
    'superAdmin.manageUsers': 'Manage users',
    'superAdmin.inviteAdmin': 'Invite admin',
    'superAdmin.noTenants': 'No tenants yet',
    'superAdmin.loadError': 'Error loading tenants',
    'superAdmin.cleanupData': 'Clean up global data',
    'superAdmin.cleanupDesc': 'Removes all orphaned data without tenant assignment (tenant_id = NULL) from the database. This action cannot be undone.',
    'superAdmin.cleaning': 'Cleaning...',
    'superAdmin.cleanupButton': 'Delete global data',
    'superAdmin.inviteTenantAdmin': 'Invite Tenant Admin',
    'superAdmin.inviteTenantAdminDesc': 'Invite an administrator for tenant "{tenant}". The invited user will receive admin rights for this tenant.',
    'superAdmin.emailAddress': 'Email address',
    'superAdmin.sendInvite': 'Send invitation',
    'superAdmin.editTenant': 'Edit tenant',
    'superAdmin.editTenantDesc': 'Change the name of tenant "{tenant}".',
    'superAdmin.companyName': 'Company name',
    'superAdmin.saving': 'Saving...',
    'superAdmin.save': 'Save',
    'superAdmin.deleteTenant': 'Really delete tenant?',
    'superAdmin.deleteTenantDesc': 'Do you really want to delete tenant "{tenant}"? This action cannot be undone and all associated data will also be deleted.',
    'superAdmin.deleting': 'Deleting...',
    'superAdmin.delete': 'Delete',
    'superAdmin.usersAndRoles': 'Users and their roles in this tenant',
    'superAdmin.addUser': 'Add user',
    'superAdmin.addUserHint': 'Enter the email address of an existing user to assign them to this tenant.',
    'superAdmin.adding': 'Loading...',
    'superAdmin.add': 'Add',
    'superAdmin.role': 'Role',
    'superAdmin.roleUser': 'User',
    'superAdmin.roleTenantAdmin': 'Tenant Admin',
    'superAdmin.noUsers': 'No users in this tenant',
    
    // Access Logs
    'accessLogs.title': 'Access Logs',
    'accessLogs.noPermission': 'No permission',
    'accessLogs.totalEvents': 'Total Events',
    'accessLogs.logins': 'Logins',
    'accessLogs.logouts': 'Logouts',
    'accessLogs.pageViews': 'Page Views',
    'accessLogs.actions': 'Actions',
    'accessLogs.uniqueUsers': 'Active Users',
    'accessLogs.userAccessTracking': 'User Access Tracking',
    'accessLogs.filter': 'Filter',
    'accessLogs.excelExport': 'Excel Export',
    'accessLogs.eventType': 'Event Type',
    'accessLogs.all': 'All',
    'accessLogs.login': 'Login',
    'accessLogs.logout': 'Logout',
    'accessLogs.pageView': 'Page View',
    'accessLogs.action': 'Action',
    'accessLogs.user': 'User',
    'accessLogs.userPlaceholder': 'Name or email...',
    'accessLogs.fromDate': 'From Date',
    'accessLogs.toDate': 'To Date',
    'accessLogs.resetFilters': 'Reset filters',
    'accessLogs.entries': 'entries',
    'accessLogs.entry': 'entry',
    'accessLogs.of': 'of',
    'accessLogs.total': 'total',
    'accessLogs.timestamp': 'Timestamp',
    'accessLogs.event': 'Event',
    'accessLogs.page': 'Page',
    'accessLogs.userAgent': 'User Agent',
    'accessLogs.noEntries': 'No entries found',
    'accessLogs.noLogs': 'No access logs available',
    'accessLogs.unknown': 'Unknown',
    'accessLogs.exported': 'entries exported',
    'accessLogs.exportError': 'Error exporting to Excel',
    'accessLogs.loadError': 'Error loading access logs',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored === 'de' || stored === 'en') ? stored : 'de';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
