import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  de: {
    // Navigation
    'nav.cockpit': 'Cockpit',
    'nav.projects': 'Projekte',
    'nav.products': 'Produkte',
    'nav.customers': 'Kunden',
    'nav.collections': 'Sammlungen',
    'nav.reports': 'Reports',
    'nav.administration': 'Administration',
    'nav.admin': 'Benutzerverwaltung',
    'nav.dataHub': 'Datenhub',
    'nav.logout': 'Abmelden',
    'nav.applications': 'Applikationen',
    
    // Page Titles
    'page.projects': 'Projekte',
    'page.products': 'Produkte',
    'page.customers': 'Kunden',
    'page.collections': 'Sammlungen',
    'page.applications': 'Applikationen',
    'page.admin': 'Admin',
    'page.reports': 'Reports',
    'page.dataHub': 'Datenhub',
    'page.superAdmin': 'Super Admin',
    'page.dashboard': 'Dashboard',
    'page.settings': 'Einstellungen',
    'page.crossSells': 'Cross Sells',
    
    // Search
    'search.placeholder': 'Suche nach Projekten, Produkten, Kunden...',
    'search.noResults': 'Keine Ergebnisse gefunden',
    'search.projects': 'Projekte',
    'search.products': 'Produkte',
    'search.customers': 'Kunden',
    'search.applications': 'Applikationen',
    'search.collections': 'Sammlungen',
    'search.searchProjects': 'Projekte suchen...',
    'search.searchProducts': 'Produkte suchen...',
    'search.searchCustomers': 'Kunde suchen...',
    'search.searchApplications': 'Applikationen suchen...',
    'search.searchCrossSells': 'Cross-Sells suchen...',
    
    // User Preferences
    'userPrefs.title': 'Benutzereinstellungen',
    'userPrefs.theme': 'Design',
    'userPrefs.light': 'Hell',
    'userPrefs.dark': 'Dunkel',
    'userPrefs.system': 'System',
    'userPrefs.language': 'Sprache',
    
    // Dashboard
    'dashboard.welcome': 'Willkommen',
    'dashboard.statistics': 'Statistiken',
    'dashboard.recentProjects': 'Aktuelle Projekte',
    'dashboard.actionItems': 'Aktionspunkte',
    'dashboard.gettingStarted': 'Erste Schritte',
    
    // Common Actions
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.export': 'Exportieren',
    'common.import': 'Importieren',
    'common.loading': 'Lädt...',
    'common.add': 'Hinzufügen',
    'common.remove': 'Entfernen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Zurück',
    'common.configure': 'Konfigurieren',
    'common.reset': 'Zurücksetzen',
    'common.showAll': 'Alle anzeigen',
    'common.show': 'Anzeigen',
    'common.hide': 'Ausblenden',
    'common.all': 'Alle',
    'common.none': 'Keine',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.confirm': 'Bestätigen',
    'common.reject': 'Ablehnen',
    'common.details': 'Details',
    'common.actions': 'Aktionen',
    'common.noData': 'Keine Daten vorhanden',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    
    // Table Headers - Projects
    'table.projectName': 'Projektname',
    'table.customer': 'Kunde',
    'table.application': 'Applikation',
    'table.applications': 'Applikationen',
    'table.product': 'Produkt',
    'table.products': 'Produkte',
    'table.status': 'Status',
    'table.optimizationStatus': 'Optimierungsstatus',
    'table.created': 'Erstellt',
    'table.lastModified': 'Zuletzt geändert',
    'table.productsInProject': 'Produkte im Projekt',
    'table.crossSellOpportunities': 'Cross-Sell Opportunities',
    
    // Table Headers - Products
    'table.component': 'Bauteil',
    'table.manufacturer': 'Hersteller',
    'table.productFamily': 'Produktfamilie',
    'table.description': 'Beschreibung',
    'table.tags': 'Tags',
    'table.price': 'Preis',
    'table.priceTooltip': 'in €/pcs',
    'table.leadTime': 'Lieferzeit',
    'table.leadTimeTooltip': 'in Wochen',
    'table.inventory': 'Lagerbestand',
    'table.inventoryTooltip': 'in pcs',
    'table.crossSells': 'Cross-Sells',
    'table.link': 'Link',
    'table.alternatives': 'Alternativen',
    'table.reason': 'Grund',
    'table.score': 'Score',
    'table.recommendation': 'Empfehlung',
    'table.action': 'Aktion',
    
    // Table Headers - Customers
    'table.customerName': 'Kunde',
    'table.industry': 'Branche',
    'table.country': 'Land',
    'table.city': 'Stadt',
    'table.category': 'Kategorie',
    'table.projectCount': 'Projekte',
    
    // Optimization Status
    'status.new': 'Neu',
    'status.open': 'Offen',
    'status.review': 'Prüfung',
    'status.validation': 'Validierung',
    'status.completed': 'Abgeschlossen',
    'status.identified': 'Identifiziert',
    'status.suggested': 'Vorgeschlagen',
    'status.accepted': 'Akzeptiert',
    'status.registered': 'Registriert',
    'status.rejected': 'Abgelehnt',
    
    // Filter Options
    'filter.all': 'Alle',
    'filter.allProjects': 'Alle Projekte',
    'filter.allProducts': 'Alle Produkte',
    'filter.allCustomers': 'Alle Kunden',
    'filter.allApplications': 'Alle Applikationen',
    'filter.allCategories': 'Alle Kategorien',
    'filter.allIndustries': 'Alle Branchen',
    'filter.allCountries': 'Alle Länder',
    'filter.allCities': 'Alle Städte',
    'filter.favorites': 'Favoriten',
    'filter.recent': 'Zuletzt',
    'filter.status': 'Status',
    'filter.productFamily': 'Produktfamilie',
    'filter.manufacturer': 'Hersteller',
    'filter.lifecycle': 'Lebenszyklus',
    'filter.npiOnly': 'Nur NPI',
    'filter.topOnly': 'Nur Top',
    
    // Pagination
    'pagination.results': 'Ergebnisse',
    'pagination.resultsPerPage': 'Ergebnisse pro Seite',
    'pagination.of': 'von',
    'pagination.previous': 'Zurück',
    'pagination.next': 'Weiter',
    'pagination.page': 'Seite',
    
    // Dashboard Widgets
    'widget.projects': 'Projekte',
    'widget.statistics': 'Statistiken',
    'widget.actionItems': 'Aktionspunkte',
    'widget.gettingStarted': 'Erste Schritte',
    'widget.optimizationStatus': 'Projekte nach Optimierungsstatus',
    'widget.npiProducts': 'NPI Produkte',
    'widget.addedProducts': 'Hinzugefügte Produkte',
    'widget.loginActivity': 'Login Aktivität',
    'widget.accessStats': 'Zugriffs-Statistiken',
    'widget.search': 'Suche',
    
    // Project Detail
    'project.metadata': 'Projektdetails',
    'project.createdAt': 'Erstellt',
    'project.customer': 'Kunde',
    'project.application': 'Applikation',
    'project.products': 'Produkte',
    'project.crossSells': 'Cross-Sells',
    'project.alternatives': 'Alternativen',
    'project.noProducts': 'Keine Produkte in diesem Projekt',
    'project.noCrossSells': 'Keine Cross-Sell Opportunities verfügbar',
    'project.addProduct': 'Produkt hinzufügen',
    'project.removeProduct': 'Produkt entfernen',
    
    // Product Detail
    'product.details': 'Produktdetails',
    'product.addToCollection': 'Zur Sammlung hinzufügen',
    'product.selectCollection': 'Sammlung auswählen',
    'product.createCollection': 'Neue Sammlung erstellen',
    'product.collectionName': 'Sammlungsname',
    'product.collectionCreated': 'Sammlung erstellt',
    'product.addedToCollection': 'Produkt zur Sammlung hinzugefügt',
    'product.alreadyInCollection': 'Produkt ist bereits in dieser Sammlung',
    
    // Customer Detail
    'customer.details': 'Kundendetails',
    'customer.location': 'Standort',
    'customer.viewProjects': 'Projekte anzeigen',
    
    // Dialogs
    'dialog.confirmDelete': 'Löschen bestätigen',
    'dialog.deleteMessage': 'Möchten Sie diesen Eintrag wirklich löschen?',
    'dialog.inviteUser': 'Benutzer einladen',
    'dialog.addToCollection': 'Zur Sammlung hinzufügen',
    'dialog.removeReason': 'Grund für Entfernung',
    
    // Toast Messages
    'toast.success': 'Erfolgreich',
    'toast.error': 'Fehler',
    'toast.saved': 'Gespeichert',
    'toast.deleted': 'Gelöscht',
    'toast.added': 'Hinzugefügt',
    'toast.removed': 'Entfernt',
    'toast.updated': 'Aktualisiert',
    'toast.loadError': 'Fehler beim Laden',
    'toast.saveError': 'Fehler beim Speichern',
    'toast.deleteError': 'Fehler beim Löschen',
    
    // Admin
    'admin.users': 'Benutzer',
    'admin.inviteUser': 'Benutzer einladen',
    'admin.role': 'Rolle',
    'admin.lastLogin': 'Letzter Login',
    'admin.pendingInvitation': 'Einladung ausstehend',
    'admin.deleteUser': 'Benutzer löschen',
    'admin.userManagement': 'Benutzerverwaltung',
    
    // Removal Reasons
    'removal.technicalFit': 'Technischer Fit',
    'removal.commercialFit': 'Commercial Fit',
    'removal.otherSupplier': 'Anderer Lieferant',
    'removal.noNeed': 'Kein Bedarf',
    'removal.other': 'Sonstige',
    
    // Product Lifecycle
    'lifecycle.comingSoon': 'Coming Soon',
    'lifecycle.active': 'Active',
    'lifecycle.nfnd': 'NFND',
    'lifecycle.discontinued': 'Discontinued',
    
    // Empty States
    'empty.projects': 'Keine Projekte gefunden',
    'empty.products': 'Keine Produkte gefunden',
    'empty.customers': 'Keine Kunden gefunden',
    'empty.collections': 'Keine Sammlungen gefunden',
    'empty.applications': 'Keine Applikationen gefunden',
    'empty.crossSells': 'Keine Cross-Sells verfügbar',
    'empty.alternatives': 'Keine Alternativen verfügbar',
    
    // Column Visibility
    'columns.configure': 'Spalten konfigurieren',
    'columns.reset': 'Zurücksetzen',
    'columns.showAll': 'Alle anzeigen',
    'columns.hideAll': 'Alle ausblenden',
    
    // Quick Filters - Projects
    'quickFilter.all': 'Alle',
    'quickFilter.favorites': 'Favoriten',
    'quickFilter.recent': 'Zuletzt',
    'quickFilter.new': 'Neu',
    'quickFilter.review': 'Prüfen',
    
    // Collections
    'collections.title': 'Sammlungen',
    'collections.new': 'Neue Sammlung',
    'collections.edit': 'Sammlung bearbeiten',
    'collections.create': 'Neue Sammlung erstellen',
    'collections.name': 'Name',
    'collections.description': 'Beschreibung (optional)',
    'collections.visibility': 'Sichtbarkeit',
    'collections.visibilityPrivate': 'Nur für mich',
    'collections.visibilitySelected': 'Ausgewählte Nutzer',
    'collections.visibilityOrganization': 'Gesamte Organisation',
    'collections.shareWith': 'Mit Nutzern teilen',
    'collections.selectUser': 'Nutzer auswählen...',
    'collections.products': 'Produkte',
    'collections.createdBy': 'Erstellt von',
    'collections.noCollections': 'Noch keine Sammlungen vorhanden',
    'collections.noProducts': 'Diese Sammlung enthält keine Produkte',
    'collections.confirmDelete': 'Sammlung wirklich löschen?',
    'collections.updated': 'Sammlung aktualisiert',
    'collections.created': 'Sammlung erstellt',
    'collections.deleted': 'Sammlung gelöscht',
    'collections.productRemoved': 'Produkt entfernt',
    'collections.saveError': 'Fehler beim Speichern',
    'collections.selectProducts': 'Produkte auswählen',
    
    // Applications
    'applications.title': 'Applikationen',
    'applications.relatedProduct': 'Zugehöriges Produkt',
    'applications.noApplications': 'Keine Applikationen gefunden',
    'applications.tryDifferentSearch': 'Versuchen Sie einen anderen Suchbegriff',
    'applications.startUpload': 'Beginnen Sie mit dem Hochladen von Applikationsdaten',
    'applications.details': 'Applikationsdetails und Informationen',
    'applications.industry': 'Industrie',
    'applications.trends': 'Trends',
    'applications.productFamilies': 'Product Families',
    'applications.blockDiagram': 'Blockdiagramm',
    'applications.noDetails': 'Keine detaillierten Informationen für diese Applikation verfügbar.',
    
    // Action Items
    'actionItems.title': 'Action Items',
    'actionItems.new': 'Neu',
    'actionItems.edit': 'Action Item bearbeiten',
    'actionItems.create': 'Neues Action Item',
    'actionItems.titleLabel': 'Titel',
    'actionItems.titlePlaceholder': 'Titel des Action Items',
    'actionItems.descriptionLabel': 'Beschreibung',
    'actionItems.descriptionPlaceholder': 'Optionale Beschreibung',
    'actionItems.priority': 'Priorität',
    'actionItems.priorityLow': 'Niedrig',
    'actionItems.priorityMedium': 'Mittel',
    'actionItems.priorityHigh': 'Hoch',
    'actionItems.statusOpen': 'Offen',
    'actionItems.statusInProgress': 'In Bearbeitung',
    'actionItems.statusCompleted': 'Abgeschlossen',
    'actionItems.assignedTo': 'Zugewiesen an',
    'actionItems.assignMyself': 'Mich selbst',
    'actionItems.assignment': 'Zuordnung (optional)',
    'actionItems.project': 'Projekt',
    'actionItems.customer': 'Kunde',
    'actionItems.selectProject': 'Projekt auswählen...',
    'actionItems.selectCustomer': 'Kunde auswählen...',
    'actionItems.dueDate': 'Fälligkeitsdatum (optional)',
    'actionItems.noItems': 'Noch keine Action Items. Erstellen Sie Ihr erstes!',
    'actionItems.sortByCreation': 'Nach Erstellung',
    'actionItems.sortByPriority': 'Nach Priorität',
    'actionItems.sortByDueDate': 'Nach Fälligkeit',
    'actionItems.updated': 'Action Item aktualisiert',
    'actionItems.created': 'Action Item erstellt',
    'actionItems.deleted': 'Action Item gelöscht',
    'actionItems.saveError': 'Fehler beim Speichern',
    
    // Search Widget
    'searchWidget.title': 'Opportunity Optimizer',
    'searchWidget.subtitle': 'Finden Sie Cross-Selling und Up-Selling Potenziale in Ihren Kundenprojekten',
    'searchWidget.placeholder': 'Suchen Sie nach Kunden, Projekten, Applikationen oder Produkten...',
    'searchWidget.searching': 'Suche nach',
    'searchWidget.noResults': 'Keine Ergebnisse gefunden. Laden Sie Daten im Datenhub hoch, um zu beginnen.',
    'searchWidget.recentlyViewed': 'Zuletzt angesehen',
    'searchWidget.crossSellOpportunities': 'Cross-Selling Möglichkeiten',
    
    // Statistics Widget
    'statistics.projects': 'Projekte',
    'statistics.products': 'Produkte',
    'statistics.crossSelling': 'Cross-Selling',
    'statistics.inDatabase': 'In der Datenbank',
    'statistics.available': 'Verfügbar',
    'statistics.opportunities': 'Möglichkeiten',
    'statistics.projectOverview': 'Projektübersicht',
    'statistics.allActiveProjects': 'Alle aktiven Kundenprojekte in der Datenbank',
    'statistics.productCatalog': 'Produktkatalog',
    'statistics.allAvailableProducts': 'Alle verfügbaren Produkte für Optimierungen',
    'statistics.crossSellingPotential': 'Cross-Selling Potenzial',
    'statistics.identifiedOpportunities': 'Identifizierte Verkaufschancen für zusätzliche Produkte',
    
    // Optimization Status Widget
    'optimizationStatus.title': 'Projekte nach Optimierungsstatus',
    'optimizationStatus.allTenants': 'Alle Mandanten',
    'optimizationStatus.aggregatedDistribution': 'Aggregierte Verteilung aller Projekte aus allen Mandanten nach Status',
    'optimizationStatus.distribution': 'Verteilung der Projekte nach Status im ausgewählten Zeitraum',
    'optimizationStatus.total': 'Gesamt',
    'optimizationStatus.totalAllTenants': 'Gesamt (Alle Mandanten)',
    'optimizationStatus.projects': 'Projekte',
    'optimizationStatus.projectsCrossTenanت': 'Projekte mandantenübergreifend',
    'optimizationStatus.noProjectsInTenants': 'Keine Projekte in den Mandanten gefunden',
    'optimizationStatus.noProjectsInTimeframe': 'Keine Projekte im ausgewählten Zeitraum',
    'optimizationStatus.ensureTenantsHaveData': 'Stellen Sie sicher, dass Mandanten Projektdaten hochgeladen haben',
    'optimizationStatus.tryLongerTimeframe': 'Versuchen Sie einen längeren Zeitraum oder laden Sie Projektdaten hoch',
    'optimizationStatus.distributionByStatus': 'Verteilung nach Status',
    'optimizationStatus.projectCount': 'Anzahl Projekte',
    'optimizationStatus.1month': '1 Monat',
    'optimizationStatus.3months': '3 Monate',
    'optimizationStatus.6months': '6 Monate',
    'optimizationStatus.12months': '12 Monate',
    
    // Projects Widget
    'projectsWidget.showAll': 'Alle {count} Projekte anzeigen',
    'projectsWidget.noProjects': 'Keine Projekte gefunden',
    'projectsWidget.customer': 'Kunde',
    'projectsWidget.application': 'Applikation',
    'projectsWidget.created': 'Erstellt',
    'projectsWidget.modified': 'Geändert',
    'projectsWidget.status': 'Status',
    
    // Admin Page
    'admin.title': 'Benutzerverwaltung',
    'admin.description': 'Verwalten Sie Benutzer, deren Rollen und Einstellungen',
    'admin.usersTab': 'Benutzer',
    'admin.preferencesTab': 'Benutzer-Einstellungen',
    'admin.inviteButton': 'Benutzer einladen',
    'admin.inviteDialogTitle': 'Neuen Benutzer einladen',
    'admin.inviteDialogDesc': 'Senden Sie eine Einladungs-E-Mail an einen neuen Benutzer',
    'admin.firstName': 'Vorname',
    'admin.lastName': 'Nachname',
    'admin.email': 'E-Mail-Adresse',
    'admin.roleLabel': 'Rolle',
    'admin.roleUser': 'Benutzer',
    'admin.roleTenantAdmin': 'Tenant Admin',
    'admin.registeredUsers': 'Bereits registrierte Benutzer',
    'admin.registeredUsersHint': 'Diese E-Mail-Adressen sind bereits registriert',
    'admin.sendInvite': 'Einladung senden',
    'admin.sending': 'Wird gesendet...',
    'admin.totalUsers': 'Benutzer gesamt',
    'admin.registeredUsersCount': 'Registrierte Benutzer',
    'admin.admins': 'Administratoren',
    'admin.adminsCount': 'Mit Admin-Rechten',
    'admin.recentActivity': 'Kürzlich aktiv',
    'admin.lastDays': 'Letzte 7 Tage',
    'admin.searchUsers': 'Benutzer suchen...',
    'admin.name': 'Name',
    'admin.registered': 'Registriert',
    'admin.noUsers': 'Keine Benutzer gefunden',
    'admin.resendInvite': 'Einladung erneut senden',
    'admin.makeAdmin': 'Als Admin setzen',
    'admin.removeAdmin': 'Admin-Rechte entfernen',
    'admin.confirmDeleteTitle': 'Benutzer löschen',
    'admin.confirmDeleteDesc': 'Sind Sie sicher, dass Sie den Benutzer "{email}" löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'admin.deleting': 'Wird gelöscht...',
    'admin.noTenantSelected': 'Kein Mandant ausgewählt. Bitte wählen Sie einen Mandanten in der Seitenleiste aus.',
    'admin.backToSuperAdmin': 'Zurück zum Super-Admin Dashboard',
    
    // DataHub
    'dataHub.title': 'Datenhub',
    'dataHub.description': 'Laden Sie Ihre Daten hoch und verwalten Sie Ihre Uploads',
    'dataHub.removeDuplicates': 'Duplikate entfernen',
    'dataHub.processing': 'Wird verarbeitet...',
    'dataHub.uploadXlsCsv': 'XLS/CSV hochladen',
    'dataHub.clearTable': 'Tabelle leeren',
    'dataHub.uploadHistory': 'Upload-Historie',
    'dataHub.uploadHistoryDesc': 'Übersicht Ihrer hochgeladenen Datensätze',
    'dataHub.deleteSelected': 'Ausgewählte löschen',
    'dataHub.filename': 'Dateiname',
    'dataHub.dataType': 'Datentyp',
    'dataHub.uploadDate': 'Upload-Datum',
    'dataHub.rowCount': 'Anzahl Zeilen',
    'dataHub.statusLabel': 'Status',
    'dataHub.statusSuccess': 'Erfolgreich',
    'dataHub.statusFailed': 'Fehlgeschlagen',
    'dataHub.noUploads': 'Keine Uploads vorhanden. Laden Sie Dateien hoch, um zu beginnen.',
    'dataHub.confirmDelete': 'Möchten Sie diesen Upload wirklich löschen?',
    'dataHub.confirmDeleteMultiple': 'Möchten Sie {count} Upload(s) wirklich löschen?',
    'dataHub.confirmClearTable': 'Tabelle leeren bestätigen',
    'dataHub.confirmClearTableDesc': 'Sind Sie sicher, dass Sie alle Einträge aus "{table}" löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'dataHub.clearing': 'Wird geleert...',
    'dataHub.clearTableButton': 'Tabelle leeren',
    'dataHub.noDuplicates': 'Keine Duplikate gefunden',
    'dataHub.duplicatesRemoved': '{count} Duplikate wurden erfolgreich entfernt',
    
    // Data Types
    'dataType.customer_projects': 'Kundenprojekte',
    'dataType.customer_projects_desc': 'Kunde, Projektname, Applikation, Produkt, Opportunity Creation Date',
    'dataType.customers': 'Kunden',
    'dataType.customers_desc': 'Kundenname, Branche, Land, Stadt, Kundenkategorie',
    'dataType.app_insights': 'App Insights',
    'dataType.app_insights_desc': 'Application, Application_Description, Application_BlockDiagram, Application_Trends, Industry, Product_Family_1-5',
    'dataType.applications': 'Applikationen',
    'dataType.applications_desc': 'Applikation, zugehöriges_Produkt',
    'dataType.products': 'Produkte',
    'dataType.products_desc': 'Produkt, Produktfamilie, Produktbeschreibung, Hersteller, Preis, Inventory, Lead_Time, Lifecycle, NPI, Top_Seller, Link_Herstellerseite',
    'dataType.cross_sells': 'Cross-Sells',
    'dataType.cross_sells_desc': 'Applikation, Basis_Produkt, Cross_Sell_Produkt, Rec_Source, Rec_Score',
    'dataType.product_alternatives': 'Produktalternativen',
    'dataType.product_alternatives_desc': 'Basis_Produkt, Alternatives_Produkt, Similarity',
    
    // Column Visibility
    'columns.title': 'Spalten',
    'columns.resetAll': 'Alle zurücksetzen',
  },
  en: {
    // Navigation
    'nav.cockpit': 'Cockpit',
    'nav.projects': 'Projects',
    'nav.products': 'Products',
    'nav.customers': 'Customers',
    'nav.collections': 'Collections',
    'nav.reports': 'Reports',
    'nav.administration': 'Administration',
    'nav.admin': 'Admin',
    'nav.dataHub': 'Data Hub',
    'nav.logout': 'Logout',
    'nav.applications': 'Applications',
    
    // Page Titles
    'page.projects': 'Projects',
    'page.products': 'Products',
    'page.customers': 'Customers',
    'page.collections': 'Collections',
    'page.applications': 'Applications',
    'page.admin': 'Admin',
    'page.reports': 'Reports',
    'page.dataHub': 'Data Hub',
    'page.superAdmin': 'Super Admin',
    'page.dashboard': 'Dashboard',
    'page.settings': 'Settings',
    'page.crossSells': 'Cross Sells',
    
    // Search
    'search.placeholder': 'Search for projects, products, customers...',
    'search.noResults': 'No results found',
    'search.projects': 'Projects',
    'search.products': 'Products',
    'search.customers': 'Customers',
    'search.applications': 'Applications',
    'search.collections': 'Collections',
    'search.searchProjects': 'Search projects...',
    'search.searchProducts': 'Search products...',
    'search.searchCustomers': 'Search customers...',
    'search.searchApplications': 'Search applications...',
    'search.searchCrossSells': 'Search cross-sells...',
    
    // User Preferences
    'userPrefs.title': 'User Preferences',
    'userPrefs.theme': 'Theme',
    'userPrefs.light': 'Light',
    'userPrefs.dark': 'Dark',
    'userPrefs.system': 'System',
    'userPrefs.language': 'Language',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.statistics': 'Statistics',
    'dashboard.recentProjects': 'Recent Projects',
    'dashboard.actionItems': 'Action Items',
    'dashboard.gettingStarted': 'Getting Started',
    
    // Common Actions
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.configure': 'Configure',
    'common.reset': 'Reset',
    'common.showAll': 'Show all',
    'common.show': 'Show',
    'common.hide': 'Hide',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.reject': 'Reject',
    'common.details': 'Details',
    'common.actions': 'Actions',
    'common.noData': 'No data available',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Table Headers - Projects
    'table.projectName': 'Project Name',
    'table.customer': 'Customer',
    'table.application': 'Application',
    'table.applications': 'Applications',
    'table.product': 'Product',
    'table.products': 'Products',
    'table.status': 'Status',
    'table.optimizationStatus': 'Optimization Status',
    'table.created': 'Created',
    'table.lastModified': 'Last Modified',
    'table.productsInProject': 'Products in Project',
    'table.crossSellOpportunities': 'Cross-Sell Opportunities',
    
    // Table Headers - Products
    'table.component': 'Component',
    'table.manufacturer': 'Manufacturer',
    'table.productFamily': 'Product Family',
    'table.description': 'Description',
    'table.tags': 'Tags',
    'table.price': 'Price',
    'table.priceTooltip': 'in €/pcs',
    'table.leadTime': 'Lead Time',
    'table.leadTimeTooltip': 'in weeks',
    'table.inventory': 'Inventory',
    'table.inventoryTooltip': 'in pcs',
    'table.crossSells': 'Cross-Sells',
    'table.link': 'Link',
    'table.alternatives': 'Alternatives',
    'table.reason': 'Reason',
    'table.score': 'Score',
    'table.recommendation': 'Recommendation',
    'table.action': 'Action',
    
    // Table Headers - Customers
    'table.customerName': 'Customer',
    'table.industry': 'Industry',
    'table.country': 'Country',
    'table.city': 'City',
    'table.category': 'Category',
    'table.projectCount': 'Projects',
    
    // Optimization Status
    'status.new': 'New',
    'status.open': 'Open',
    'status.review': 'Review',
    'status.validation': 'Validation',
    'status.completed': 'Completed',
    'status.identified': 'Identified',
    'status.suggested': 'Suggested',
    'status.accepted': 'Accepted',
    'status.registered': 'Registered',
    'status.rejected': 'Rejected',
    
    // Filter Options
    'filter.all': 'All',
    'filter.allProjects': 'All Projects',
    'filter.allProducts': 'All Products',
    'filter.allCustomers': 'All Customers',
    'filter.allApplications': 'All Applications',
    'filter.allCategories': 'All Categories',
    'filter.allIndustries': 'All Industries',
    'filter.allCountries': 'All Countries',
    'filter.allCities': 'All Cities',
    'filter.favorites': 'Favorites',
    'filter.recent': 'Recent',
    'filter.status': 'Status',
    'filter.productFamily': 'Product Family',
    'filter.manufacturer': 'Manufacturer',
    'filter.lifecycle': 'Lifecycle',
    'filter.npiOnly': 'NPI Only',
    'filter.topOnly': 'Top Only',
    
    // Pagination
    'pagination.results': 'Results',
    'pagination.resultsPerPage': 'Results per page',
    'pagination.of': 'of',
    'pagination.previous': 'Previous',
    'pagination.next': 'Next',
    'pagination.page': 'Page',
    
    // Dashboard Widgets
    'widget.projects': 'Projects',
    'widget.statistics': 'Statistics',
    'widget.actionItems': 'Action Items',
    'widget.gettingStarted': 'Getting Started',
    'widget.optimizationStatus': 'Projects by Optimization Status',
    'widget.npiProducts': 'NPI Products',
    'widget.addedProducts': 'Added Products',
    'widget.loginActivity': 'Login Activity',
    'widget.accessStats': 'Access Statistics',
    'widget.search': 'Search',
    
    // Project Detail
    'project.metadata': 'Project Details',
    'project.createdAt': 'Created',
    'project.customer': 'Customer',
    'project.application': 'Application',
    'project.products': 'Products',
    'project.crossSells': 'Cross-Sells',
    'project.alternatives': 'Alternatives',
    'project.noProducts': 'No products in this project',
    'project.noCrossSells': 'No cross-sell opportunities available',
    'project.addProduct': 'Add product',
    'project.removeProduct': 'Remove product',
    
    // Product Detail
    'product.details': 'Product Details',
    'product.addToCollection': 'Add to collection',
    'product.selectCollection': 'Select collection',
    'product.createCollection': 'Create new collection',
    'product.collectionName': 'Collection name',
    'product.collectionCreated': 'Collection created',
    'product.addedToCollection': 'Product added to collection',
    'product.alreadyInCollection': 'Product is already in this collection',
    
    // Customer Detail
    'customer.details': 'Customer Details',
    'customer.location': 'Location',
    'customer.viewProjects': 'View projects',
    
    // Dialogs
    'dialog.confirmDelete': 'Confirm Delete',
    'dialog.deleteMessage': 'Are you sure you want to delete this entry?',
    'dialog.inviteUser': 'Invite User',
    'dialog.addToCollection': 'Add to Collection',
    'dialog.removeReason': 'Reason for removal',
    
    // Toast Messages
    'toast.success': 'Success',
    'toast.error': 'Error',
    'toast.saved': 'Saved',
    'toast.deleted': 'Deleted',
    'toast.added': 'Added',
    'toast.removed': 'Removed',
    'toast.updated': 'Updated',
    'toast.loadError': 'Error loading data',
    'toast.saveError': 'Error saving data',
    'toast.deleteError': 'Error deleting data',
    
    // Admin
    'admin.users': 'Users',
    'admin.inviteUser': 'Invite User',
    'admin.role': 'Role',
    'admin.lastLogin': 'Last Login',
    'admin.pendingInvitation': 'Pending Invitation',
    'admin.deleteUser': 'Delete User',
    'admin.userManagement': 'User Management',
    
    // Removal Reasons
    'removal.technicalFit': 'Technical Fit',
    'removal.commercialFit': 'Commercial Fit',
    'removal.otherSupplier': 'Other Supplier',
    'removal.noNeed': 'No Need',
    'removal.other': 'Other',
    
    // Product Lifecycle
    'lifecycle.comingSoon': 'Coming Soon',
    'lifecycle.active': 'Active',
    'lifecycle.nfnd': 'NFND',
    'lifecycle.discontinued': 'Discontinued',
    
    // Empty States
    'empty.projects': 'No projects found',
    'empty.products': 'No products found',
    'empty.customers': 'No customers found',
    'empty.collections': 'No collections found',
    'empty.applications': 'No applications found',
    'empty.crossSells': 'No cross-sells available',
    'empty.alternatives': 'No alternatives available',
    
    // Column Visibility
    'columns.configure': 'Configure columns',
    'columns.reset': 'Reset',
    'columns.showAll': 'Show all',
    'columns.hideAll': 'Hide all',
    
    // Quick Filters - Projects
    'quickFilter.all': 'All',
    'quickFilter.favorites': 'Favorites',
    'quickFilter.recent': 'Recent',
    'quickFilter.new': 'New',
    'quickFilter.review': 'Review',
    
    // Collections
    'collections.title': 'Collections',
    'collections.new': 'New Collection',
    'collections.edit': 'Edit Collection',
    'collections.create': 'Create New Collection',
    'collections.name': 'Name',
    'collections.description': 'Description (optional)',
    'collections.visibility': 'Visibility',
    'collections.visibilityPrivate': 'Only me',
    'collections.visibilitySelected': 'Selected users',
    'collections.visibilityOrganization': 'Entire organization',
    'collections.shareWith': 'Share with users',
    'collections.selectUser': 'Select user...',
    'collections.products': 'Products',
    'collections.createdBy': 'Created by',
    'collections.noCollections': 'No collections yet',
    'collections.noProducts': 'This collection contains no products',
    'collections.confirmDelete': 'Really delete collection?',
    'collections.updated': 'Collection updated',
    'collections.created': 'Collection created',
    'collections.deleted': 'Collection deleted',
    'collections.productRemoved': 'Product removed',
    'collections.saveError': 'Error saving',
    'collections.selectProducts': 'Select products',
    
    // Applications
    'applications.title': 'Applications',
    'applications.relatedProduct': 'Related Product',
    'applications.noApplications': 'No applications found',
    'applications.tryDifferentSearch': 'Try a different search term',
    'applications.startUpload': 'Start by uploading application data',
    'applications.details': 'Application details and information',
    'applications.industry': 'Industry',
    'applications.trends': 'Trends',
    'applications.productFamilies': 'Product Families',
    'applications.blockDiagram': 'Block Diagram',
    'applications.noDetails': 'No detailed information available for this application.',
    
    // Action Items
    'actionItems.title': 'Action Items',
    'actionItems.new': 'New',
    'actionItems.edit': 'Edit Action Item',
    'actionItems.create': 'New Action Item',
    'actionItems.titleLabel': 'Title',
    'actionItems.titlePlaceholder': 'Action item title',
    'actionItems.descriptionLabel': 'Description',
    'actionItems.descriptionPlaceholder': 'Optional description',
    'actionItems.priority': 'Priority',
    'actionItems.priorityLow': 'Low',
    'actionItems.priorityMedium': 'Medium',
    'actionItems.priorityHigh': 'High',
    'actionItems.statusOpen': 'Open',
    'actionItems.statusInProgress': 'In Progress',
    'actionItems.statusCompleted': 'Completed',
    'actionItems.assignedTo': 'Assigned to',
    'actionItems.assignMyself': 'Myself',
    'actionItems.assignment': 'Assignment (optional)',
    'actionItems.project': 'Project',
    'actionItems.customer': 'Customer',
    'actionItems.selectProject': 'Select project...',
    'actionItems.selectCustomer': 'Select customer...',
    'actionItems.dueDate': 'Due date (optional)',
    'actionItems.noItems': 'No action items yet. Create your first one!',
    'actionItems.sortByCreation': 'By creation',
    'actionItems.sortByPriority': 'By priority',
    'actionItems.sortByDueDate': 'By due date',
    'actionItems.updated': 'Action item updated',
    'actionItems.created': 'Action item created',
    'actionItems.deleted': 'Action item deleted',
    'actionItems.saveError': 'Error saving',
    
    // Search Widget
    'searchWidget.title': 'Opportunity Optimizer',
    'searchWidget.subtitle': 'Find cross-selling and up-selling potential in your customer projects',
    'searchWidget.placeholder': 'Search for customers, projects, applications or products...',
    'searchWidget.searching': 'Searching for',
    'searchWidget.noResults': 'No results found. Upload data in the Data Hub to get started.',
    'searchWidget.recentlyViewed': 'Recently viewed',
    'searchWidget.crossSellOpportunities': 'Cross-Selling Opportunities',
    
    // Statistics Widget
    'statistics.projects': 'Projects',
    'statistics.products': 'Products',
    'statistics.crossSelling': 'Cross-Selling',
    'statistics.inDatabase': 'In database',
    'statistics.available': 'Available',
    'statistics.opportunities': 'Opportunities',
    'statistics.projectOverview': 'Project Overview',
    'statistics.allActiveProjects': 'All active customer projects in database',
    'statistics.productCatalog': 'Product Catalog',
    'statistics.allAvailableProducts': 'All available products for optimizations',
    'statistics.crossSellingPotential': 'Cross-Selling Potential',
    'statistics.identifiedOpportunities': 'Identified sales opportunities for additional products',
    
    // Optimization Status Widget
    'optimizationStatus.title': 'Projects by Optimization Status',
    'optimizationStatus.allTenants': 'All Tenants',
    'optimizationStatus.aggregatedDistribution': 'Aggregated distribution of all projects from all tenants by status',
    'optimizationStatus.distribution': 'Distribution of projects by status in selected time frame',
    'optimizationStatus.total': 'Total',
    'optimizationStatus.totalAllTenants': 'Total (All Tenants)',
    'optimizationStatus.projects': 'Projects',
    'optimizationStatus.projectsCrossTenants': 'Projects across tenants',
    'optimizationStatus.noProjectsInTenants': 'No projects found in tenants',
    'optimizationStatus.noProjectsInTimeframe': 'No projects in selected time frame',
    'optimizationStatus.ensureTenantsHaveData': 'Make sure tenants have uploaded project data',
    'optimizationStatus.tryLongerTimeframe': 'Try a longer time frame or upload project data',
    'optimizationStatus.distributionByStatus': 'Distribution by status',
    'optimizationStatus.projectCount': 'Number of projects',
    'optimizationStatus.1month': '1 month',
    'optimizationStatus.3months': '3 months',
    'optimizationStatus.6months': '6 months',
    'optimizationStatus.12months': '12 months',
    
    // Projects Widget
    'projectsWidget.showAll': 'Show all {count} projects',
    'projectsWidget.noProjects': 'No projects found',
    'projectsWidget.customer': 'Customer',
    'projectsWidget.application': 'Application',
    'projectsWidget.created': 'Created',
    'projectsWidget.modified': 'Modified',
    'projectsWidget.status': 'Status',
    
    // Admin Page
    'admin.title': 'User Management',
    'admin.description': 'Manage users, their roles and settings',
    'admin.usersTab': 'Users',
    'admin.preferencesTab': 'User Preferences',
    'admin.inviteButton': 'Invite User',
    'admin.inviteDialogTitle': 'Invite New User',
    'admin.inviteDialogDesc': 'Send an invitation email to a new user',
    'admin.firstName': 'First Name',
    'admin.lastName': 'Last Name',
    'admin.email': 'Email Address',
    'admin.roleLabel': 'Role',
    'admin.roleUser': 'User',
    'admin.roleTenantAdmin': 'Tenant Admin',
    'admin.registeredUsers': 'Already registered users',
    'admin.registeredUsersHint': 'These email addresses are already registered',
    'admin.sendInvite': 'Send Invitation',
    'admin.sending': 'Sending...',
    'admin.totalUsers': 'Total Users',
    'admin.registeredUsersCount': 'Registered users',
    'admin.admins': 'Administrators',
    'admin.adminsCount': 'With admin rights',
    'admin.recentActivity': 'Recently Active',
    'admin.lastDays': 'Last 7 days',
    'admin.searchUsers': 'Search users...',
    'admin.name': 'Name',
    'admin.registered': 'Registered',
    'admin.noUsers': 'No users found',
    'admin.resendInvite': 'Resend Invitation',
    'admin.makeAdmin': 'Make Admin',
    'admin.removeAdmin': 'Remove Admin Rights',
    'admin.confirmDeleteTitle': 'Delete User',
    'admin.confirmDeleteDesc': 'Are you sure you want to delete the user "{email}"? This action cannot be undone.',
    'admin.deleting': 'Deleting...',
    'admin.noTenantSelected': 'No tenant selected. Please select a tenant from the sidebar.',
    'admin.backToSuperAdmin': 'Back to Super Admin Dashboard',
    
    // DataHub
    'dataHub.title': 'Data Hub',
    'dataHub.description': 'Upload your data and manage your uploads',
    'dataHub.removeDuplicates': 'Remove Duplicates',
    'dataHub.processing': 'Processing...',
    'dataHub.uploadXlsCsv': 'Upload XLS/CSV',
    'dataHub.clearTable': 'Clear Table',
    'dataHub.uploadHistory': 'Upload History',
    'dataHub.uploadHistoryDesc': 'Overview of your uploaded datasets',
    'dataHub.deleteSelected': 'Delete Selected',
    'dataHub.filename': 'Filename',
    'dataHub.dataType': 'Data Type',
    'dataHub.uploadDate': 'Upload Date',
    'dataHub.rowCount': 'Row Count',
    'dataHub.statusLabel': 'Status',
    'dataHub.statusSuccess': 'Success',
    'dataHub.statusFailed': 'Failed',
    'dataHub.noUploads': 'No uploads yet. Upload files to get started.',
    'dataHub.confirmDelete': 'Do you really want to delete this upload?',
    'dataHub.confirmDeleteMultiple': 'Do you really want to delete {count} upload(s)?',
    'dataHub.confirmClearTable': 'Confirm Clear Table',
    'dataHub.confirmClearTableDesc': 'Are you sure you want to delete all entries from "{table}"? This action cannot be undone.',
    'dataHub.clearing': 'Clearing...',
    'dataHub.clearTableButton': 'Clear Table',
    'dataHub.noDuplicates': 'No duplicates found',
    'dataHub.duplicatesRemoved': '{count} duplicates were successfully removed',
    
    // Data Types
    'dataType.customer_projects': 'Customer Projects',
    'dataType.customer_projects_desc': 'Customer, Project Name, Application, Product, Opportunity Creation Date',
    'dataType.customers': 'Customers',
    'dataType.customers_desc': 'Customer Name, Industry, Country, City, Customer Category',
    'dataType.app_insights': 'App Insights',
    'dataType.app_insights_desc': 'Application, Application_Description, Application_BlockDiagram, Application_Trends, Industry, Product_Family_1-5',
    'dataType.applications': 'Applications',
    'dataType.applications_desc': 'Application, Related_Product',
    'dataType.products': 'Products',
    'dataType.products_desc': 'Product, Product Family, Product Description, Manufacturer, Price, Inventory, Lead_Time, Lifecycle, NPI, Top_Seller, Manufacturer_Link',
    'dataType.cross_sells': 'Cross-Sells',
    'dataType.cross_sells_desc': 'Application, Base_Product, Cross_Sell_Product, Rec_Source, Rec_Score',
    'dataType.product_alternatives': 'Product Alternatives',
    'dataType.product_alternatives_desc': 'Base_Product, Alternative_Product, Similarity',
    
    // Column Visibility
    'columns.title': 'Columns',
    'columns.resetAll': 'Reset All',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored === 'de' || stored === 'en') ? stored : 'de';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
